### ISSUE TITLE
simple-system-monitor@ariel: Desklet not work if no internet connection at launching PC

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-desklets#10]
Hi. I tried this desklet. It work for me after installation. But it has issue:
   If I launched my laptop & internet is ON, then no problem. Desklet appear on screen & work. 
   But if I launched laptop & no Internet connection then an error message appear saying: "Cinnamon undergo error due to one of applet or extension not worked. Disable this applet or extension to avoid this message". In this case this desklet do not appear on screen (not started) !!
   The desklet do not start at laptop start if at laptop start no Internet available !! 
   I discover this issue when I powered on my laptop at a time when my router was switch OFF.

UUID: simple-system-monitor@ariel

**Comment by JosephMcc** [comment]
Fixed the issue title to use proper formatting. Don't think the dramatic !! are really needed either.

**Comment by Nokia808** [comment]
By the way, my system is:
Fedora 24 x64 bit Cinnamon edition on Lenovo ThinkPad e550 with 8GB RAM + Inter Core i7-5500U CPU @ 2.40GHz x 2

**Comment by arielandrade** [comment]
Sorry for the delay, I'll take a look at it.
