### ISSUE TITLE
Desklet Bug

### ISSUE THREAD

**Issue by dwh367** [linuxmint/cinnamon-spices-desklets#1032]
### Desklet version/Build date

1.4

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C+8G × 2

### Desklet name and maintainer

hostcheck@schorschii @schorschii

### What happened?

Host Check Desklet will not load in Mint 21.3

### Other information

On Mint 21.2 Host Check would not show custom desklet label

**Comment by schorschii** [comment]
Found it... Mint 21.3 uses a new version of libsoup.
