### ISSUE TITLE
yarr@jtoberling: Stuck at "Loading: feeds", desklet blank as of latest Cinnamon version (6.0.4) on LMDE 6

### ISSUE THREAD

**Issue by emirvmendoza** [linuxmint/cinnamon-spices-desklets#1036]
### Desklet version/Build date

1.0.0 (2023-10-17 19:51:40)

### Cinnamon version

6.0.4

### Distribution

LMDE 6

### Desklet name and maintainer

yarr@jtoberling @jtoberling

### What happened?

@jtoberling

yarr is stuck at "Loading: feeds", desklet blank after upgrading to latest Cinnamon version (6.0.4) on LMDE 6.  Refreshing does not work.

### Other information

![Screenshot from 2024-01-16 10-21-44](https://github.com/linuxmint/cinnamon-spices-desklets/assets/154249992/edc184c5-927c-4034-a99f-7e245ec0ab35)

![Screenshot from 2024-01-16 10-23-01](https://github.com/linuxmint/cinnamon-spices-desklets/assets/154249992/6d3dfd6a-9e64-4d1d-ab9a-6853a6d9ddd9)

**Comment by jtoberling** [comment]
Looking into...
Replicated under Linux Mint 21.3 Virginia.

**Comment by jtoberling** [comment]
It seems default imports has been changed so added ByteArray to imports. 
@emirvmendoza  Pls. check - next version is updating soon...

**Comment by emirvmendoza** [comment]
> It seems default imports has been changed so added ByteArray to imports. @emirvmendoza Pls. check - next version is updating soon...

Updated to latest version, feeds appear normally now.  Thank you very much for the swift fix.
