### ISSUE TITLE
bbcwx@oak-wood.co.uk: Feature Request Open-Meteo API

### ISSUE THREAD

**Issue by BradB58** [linuxmint/cinnamon-spices-desklets#1046]
### Desklet name and maintainer

bbcwx@oak-wood.co.uk @tipichris

### What would you like to see?

There is a new weather api called Open-Meteo that is the default weather source on my android weather app breezy-weather (here on github). I find it to be quite accurate. I think it would be an awesome addition to the weather desklet, especially in view of how many of the existing api's have become unusable or now require you to pay. I currently use open weather, but I have never been that crazy about it. It seems to miss the mark quite a bit for my area.

**Comment by rcalixte** [comment]
I can't commit to a timeline on this (though I would prefer soon than later) but on a glance, I like this service and would like to see it supported. I'm currently working on some other features for this desklet and I'll see if I can get this implemented in the same pass.

**Comment by BradB58** [comment]
@rcalixte Great work! Thank you for all of the awesome improvements!
