### ISSUE TITLE
clock@schorschii: Label not showing up

### ISSUE THREAD

**Issue by starleaf1** [linuxmint/cinnamon-spices-desklets#1049]
### Desklet version/Build date

Version 1.6 (2023-12-13 02:11:15)

### Cinnamon version

5.2.7

### Distribution

Ubuntu 22.04.3

### Graphics hardware *and* driver used

NVIDIA GeForce RTX 2060 - nouveau

### Desklet name and maintainer

clock@schorschii @schorschii

### What happened?

I use add a label, but the label doesn't show up anywhere around/on the desklet.

### Other information

![image](https://github.com/linuxmint/cinnamon-spices-desklets/assets/12312606/31b3bb5e-88c0-4ef1-afbc-d0f9a399c229)

**Comment by claudiux** [comment]
You're using `clock@schorschii` and not `analog-clock@cobinja.de` (which works very well). Please correct that in your issue.

**Comment by schorschii** [comment]
@starleaf1 As stated on the settings page, labels are only visible if decorations are enabled. See https://github.com/linuxmint/cinnamon-spices-desklets/issues/919#issuecomment-1720745474.

@claudiux My desklet works very well too?! ^^

**Comment by claudiux** [comment]
@schorschii Sorry, but enabling or disabling decorations, the label is not visible.

**Comment by schorschii** [comment]
Hmm, I'm not able to reproduce this issue. Works like charm:
![Screenshot from 2024-02-08 14-51-56](https://github.com/linuxmint/cinnamon-spices-desklets/assets/17480795/b6b7e308-a6e9-472a-949e-632396853fc6)

Are you using v1.6? Or maybe you have enbaled the "Hide Decorations" option in the settings of my desklet? (This option allows the user to overwrite the global setting for one clock instance only.)

**Comment by claudiux** [comment]
Found the source of the problem: In Cinnamon settings -> Desklets -> General settings tab, I've been chosen "Border only". Once "Border and header" was selected, the problem disappeared.
