### ISSUE TITLE
TimeAndDate@nightflame Feature Request: time and date on one line

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-desklets#1051]
### Desklet name and maintainer

TimeAndDate@nightflame

### What would you like to see?

How much work would it be to put a "1 line/2 line" question in the config?  <br>Or some such question, a simple y/n option of some sort would work.

There are times I'd like to conserve vertical space and have the Date then time all on one line.  
Still have different font configs, but just one line.

![Time Date](https://github.com/linuxmint/cinnamon-spices-desklets/assets/26556059/5a8aca9a-903f-46f1-abd5-8f1362d47646)
Sample

**Comment by rcalixte** [comment]
This desklet doesn't currently have a maintainer.

Are you also looking for support for a custom border size, color, or radius? If not, [this desklet](https://cinnamon-spices.linuxmint.com/desklets/view/64) should have the customization options you're looking for. If those additional customization options are needed, they could be added as well.

**Comment by ChooChooAl** [comment]
Yes, this should work.  I configured it and it looks very close to what I had designed in GIMP.

Thanks. - closed.
