### ISSUE TITLE
hostcheck@schorschii: Accumulation ping process

### ISSUE THREAD

**Issue by Gujenczek** [linuxmint/cinnamon-spices-desklets#1053]
### Desklet version/Build date

1.5

### Cinnamon version

5.2.7, 6.0.4

### Distribution

Mint 20.3, Mint 21.3

### Desklet name and maintainer

hostcheck@schorschii @schorschii

### What happened?

Hi @schorschii,
I don't know why, but during the check ping at interval in system "ping" process isn't stop after execution. In 'gnome-system-monitor' or '$ ps -e | grep ping' the ping process still works like a zombie and can not kill this 'ping' process.

Process is at: cinnamon-lancher -> cinnamon ($ cinnamon --replace) -> ping
Restart or kill 'cinnamon' is not the solution.
$ pkill ping -> not working
$ pkill cinnamon -> kill all session with 'ping'

Maybe
desklet.js:147 -> GLib.spawn_close_pid(child_pid);
not working correctly.

**Comment by schorschii** [comment]
@Gujenczek Thanks for reporting. Can you please test the new version 1.5.1?

**Comment by Gujenczek** [comment]
The ping bug is fixed. System work correctly.
