### ISSUE TITLE
 Yahoo Finance Quotes - setting personal font size

### ISSUE THREAD

**Issue by arax-1238** [linuxmint/cinnamon-spices-desklets#1075]
### Desklet name and maintainer

yfquotes@thegli @thegli

### What would you like to see?

It would be nice to be able to set your own font size in your personal settings

**Comment by thegli** [comment]
Hi @arax-1238 

Cinnamon's "Default font" selection affects e.g. the menu, widgets, and desklets such as this one. For my part, this one default font size works good enough for all of these elements.
Maybe you can briefly elaborate why Cinnamon's standard font selection is not sufficient for you, so I get a better understanding of this feature request.

**Comment by thegli** [comment]
Thanks for the clarifications. I will definitely have a look into this, but can't make any promises.

**Comment by thegli** [comment]
Addressed with #1090
