### ISSUE TITLE
calendar@deeppradhan : translation problem 

### ISSUE THREAD

**Issue by PRSoftware** [linuxmint/cinnamon-spices-desklets#1092]
### Desklet version/Build date

Version 1.1 (2024-03-15 19:15:01)

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Mint 21.3 Cinnamon

### Graphics hardware *and* driver used

Advanced Micro Devices, Inc. [AMD/ATI] RV710/M92 [Mobility Radeon HD 4530/4570/545v] (prog-if 00 [VGA controller])

### Desklet name and maintainer

calendar@deeppradhan @kanchudeep

### What happened?

I have created a translation file into French [fr.po.zip](https://github.com/linuxmint/cinnamon-spices-desklets/files/14623174/fr.po.zip) and put the compiled file in the dedicated directory (~/.local/share/locale/fr/LC_MESSAGES/calendar@deeppradhan.mo).
All the text in the configuration panel of the desklet if correctly translated but none of the text displayed on the desklet itself is translated: the name of days and months are always shown in English like all the other displayed words ("Next month...", "Previous month...", etc...). 
In the file "desklet.js" the following lines must be added after the line 'const UUID = "calendar@deeppradhan";'
const GLib = imports.gi.GLib;
const Gettext = imports.gettext;

Gettext.bindtextdomain(UUID, GLib.get_home_dir() + "/.local/share/locale");

function _(str) {
    return Gettext.dgettext(UUID, str);
}

**Comment by rcalixte** [comment]
Apologies, that was my oversight. The update should work once installed.
