### ISSUE TITLE
system-monitor-graph@rcassani : disk name disappears after restarting

### ISSUE THREAD

**Issue by PRSoftware** [linuxmint/cinnamon-spices-desklets#1100]
### Desklet version/Build date

1.5

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Advanced Micro Devices, Inc. [AMD/ATI] RV710/M92 [Mobility Radeon HD 4530/4570/545v] (prog-if 00 [VGA controller])

### Desklet name and maintainer

system-monitor-graph@rcassani @rcassani

### What happened?

After login or after restarting Cinnamon, the name of the hard drive (sdaX) is always replaced by 3 dots (see screen copy) 
![screen](https://github.com/linuxmint/cinnamon-spices-desklets/assets/59197612/ccc4f25c-3ef6-4124-94f0-81e30ea8538a)

I must go to the configuration options, select a directory and the select again "File system" to have the correct name displayed.

But, this name disappears again if I restart Cinnamon.

I observed the same behavior if I select a directory inside the file system instead of "File System".

**Comment by rcassani** [comment]
The name of the partition is obtained in from the `df` command, as all the "word characters"(a-z, A-Z, 0-9, and _) after a second slash. Does your partition follows a different naming? Test in the terminal: `df PATH`

In my case `df /` returns `/dev/nvme0n1p2` so the partition name `nvme0n1p2`

**Comment by PRSoftware** [comment]
The command "df /" returns "/dev/sda3" : nothing exotic ...
