### ISSUE TITLE
analog-clock@cobinja.de: some strings cannot be translated

### ISSUE THREAD

**Issue by trikaphundo** [linuxmint/cinnamon-spices-desklets#1159]
### Desklet name and maintainer

analog-clock@cobinja.de @cobinja

## The problem
Some strings in the **settings window** of the desklet are in English with no possibility to translate them.
 - Timezones and city names.
 - Theme names.
 - Buttons of the settings window.

Here you have an image showing the problem in the Catalan translation
![analog-clock-desklet](https://github.com/linuxmint/cinnamon-spices-desklets/assets/24832650/e4fb2001-a345-48e5-a2ca-34387e1823c7)

## Feature request
I think that, at the very least, theme names and buttons should be translatable.

## System info
I am on LinuxMint 21.3 with Cinnamon 6.0.4

**Comment by Cobinja** [comment]
Theme names are their own names and will not be translated.

"Apply", "Cancel" and "Ok" are translated by gtk. It seems your language installation is missing some language packs. Go to Cinnamon's setting -> Languages -> Install/Remove languages and install the missing language packs for Catalan.
