### ISSUE TITLE
Is citationsfr@mrvaykadji redundant with quoteOfTheDay@tinnu?

### ISSUE THREAD

**Issue by JessW** [linuxmint/cinnamon-spices-desklets#119]
I just noticed the citationsfr desklet, and I'm wondering if it is redundant with the quoteOfTheDay desklet?  It looks like the author of citationsfr couldn't be easily found on github (I'm the original author of the quoteOfTheDay desklet).  A quick look through the French README didn't seem to indicate any major differences from the original desklet, although my French is a bit rusty.  Now that translation support is being added to many desklets (thank you!), I think a second version of basically the same desklet is just more maintenance.  Any thoughts?

**Comment by NikoKrause** [comment]
I noticed this as well. It seems, that it's a mix of Quote of the Day and Command of the day. But in French.
The problem right now is that all quotes are still in English. It would be great, if you could guide the user to install a localized version of fortune in his language, then it would be redundant.

Can you also send a pull request and fix the author info:
https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/quoteOfTheDay%40tinnu/info.json

It's better to use the GitHub Name to be able to notify the author about issues/feature requests.

Thanks

**Comment by JessW** [comment]
Thanks, @NikoKrause, those are both great suggestions, will do!

**Comment by Ilis** [comment]
@JessW @NikoKrause 

Now **Quote of the Day** use `fortune` to get quote.

* **citationsfr** works just like older version of **Quote of the Day**, but includes one file with fr-quotes
* **Command of the day** works like newer version of **Quote of the Day**, but like `fortune` called without any parameters (it gives user one quote out of all quotes files in users language if fortunes-XX installed or all of default English quotes)

If one make settings for **Quote of the Day** to choose between *no parameter* and *file*, then desklet override functionality of both alternative desklets. Say, it will be checkbox “Use custom file”. If unchecked, then `fortune` called without file parameter, if checked, then user can choose file name.

Even more, desklet can has text field setting to give extra options for `fortune` such as `-l`, `-s`, `-o`, `-m pattern` and so on.

**Comment by JessW** [comment]
@logg

Thanks for wading through Command of the Day to see how it works, @Ilis !  I would say at the very least the name is misleading, as the readme for the desklet explains it was really just created to allow the author to run `fortune -o`, and I wonder if it has been tested with any other commands.

I am a little hesitant to add a setting to Quote of the Day to make the input file optional.  I wonder if that would seem confusing to a user who doesn't know how `fortune` works?  I think your point, Ilis, about allowing no file is that then `fortune` will automatically pick a file in the user's language, if available, did I understand that correctly?

I do like the idea of allowing additional parameters to `fortune`, as you mentioned.

I'm going to go now and update the docs for Quote of the Day to include instructions for adding localized quotes, and that may resolve the issue with citationsfr, at least.

**Comment by JessW** [comment]
Okie dokie, so.  

1. Yesterday I added some instructions to the README about installing fortunes for the user's locale.  I like your idea to add a hint in the Preferences dialog to go check the readme for help with this.
2. I also added some more instructions for creating a custom input file, based on your example of combining multiple existing fortune files (thank you!)
3. I will add a text box to the Preferences dialog to allow the user to pass additional parameters, e.g. -s, etc., to `fortune`
4. Are you saying your favorite way to run `fortune` is without passing it a file?  Now that I've compared the fortune packs for English and Russian, I think I have a better understanding of your point - there are lots more files in Russian!  What do you think if I put the "no input file" option at the bottom of the Preference dialog as an "advanced" option?  I would like a user to be able to run QotD out of the box without reading the readme and without being confused.  But I think as an English speaker I'm biased on this point, so I'd like to hear your opinion, @Ilis !

**Comment by Ilis** [comment]
> so I'd like to hear your opinion

Well, I try to explain it on my own experience.

`fortune` is my favourite “game” from that times when I used Linux via terminal. I used it as session greeter, I used it as source of some portion of text in my scripts, I used it in pipes, i. e. `fortune | cowsay`. Then every time I install new instance of Linux I starting terminal and issue a fortune command.

At the beginning I was glad I start `fortune` and get some random text. Later I found a `fortunes-ru` package with a lot of quotes and become much happier. Then I realised that more then a half of set of quotes are not interesting for me, and I sorted out how I can issue some parameters for `fortune` to get exactly what I want.

And I dreamed about to make my own set of quotes. Now I can do all above (thanks to you!).

So, my order of using is
1. Just use it with no option.
2. Use it with name of file out of standard package.
3. Use it with names of files out of standard and extra packages.
4. Use it with my own file.

```
ilis@deore ~ $ fortune
Каждый человек действует для себя, по своему плану, а выходит общее
действие, исполняется другой - высший - план, и из суровых, тонких,
гнилых биографических нитей сплетается каменная ткань Истории.
		-- М.Погодин
ilis@deore ~ $ fortune literature
My only love sprung from my only hate!
Too early seen unknown, and known too late!
		-- William Shakespeare, "Romeo and Juliet"
ilis@deore ~ $ fortune literature art
Песня - это звучание души, иногда доставляющее удовольствие окружающим.
		-- Виктор Кротов
ilis@deore ~ $ fortune ~/diamond-arm
Семё-он Семёныч!..
        — Володя
```

Note, that default behaviour of QotD is like you call `fortune literature` without full path to file.

It means that the file chooser only needed when you want to choose your own file (and you have to know how to prepare that one), ant it become unnecessary option (due to possibility to give full file name with path in option), but, certainly, more convenient to average user.

And after all I have no receipt for how better make QotD :)

**Comment by Ilis** [comment]
Now it seems to me QotD can be GUI for `fortune` with ability to show fortunes on screen using nice fonts!
![2017-06-15 22-10-42](https://user-images.githubusercontent.com/1223140/27193234-8bed38d8-5217-11e7-944a-a1a61f7ba685.png)

**Comment by JessW** [comment]
I don't think I saw your screenshot before, @Ilis , it's lovely!  

I just sent a pull request with the advanced configuration options that we talked about awhile back.  Once the update is available, let me know what you think if you get a chance!  (Apologies for the delay.)

**Comment by Ilis** [comment]
Hi, @JessW 

I checked new configuration options, it seems they work.

So, main thing of this issue is closed. Installing fortune-fr or choosing appropriate file can fully replace `citationfr` and has extra functionality. The same about `Command of the day`.

Thank you for this nice desklet!

**Comment by Ilis** [comment]
@JessW , please, would you update *.pot for new items to localize?

**Comment by JessW** [comment]
@Ilis , thank you for checking the new options, I'm glad to hear they work for you too!

@NikoKrause , I've updated the Quote of the Day desklet with some instructions for installing localized fortune files, in case you think that might be enough to deprecate citationsfr?  I also added options to pass flags to `fortune` when running Quote of the Day, possibly making Command of the Day redundant also.

**Comment by JessW** [comment]
@Ilis , I'll definitely update the *.pot file, I didn't realize I needed to do that!

**Comment by NikoKrause** [comment]
If you think that those applets are redundant, can you create a PR, which deletes those applets?

**Comment by JessW** [comment]
@NikoKrause Sure, will do.

**Comment by NikoKrause** [comment]
Closed by https://github.com/linuxmint/cinnamon-spices-desklets/pull/198
