### ISSUE TITLE
[yfquotes@thegli] Feature Request - Force Refresh

### ISSUE THREAD

**Issue by SonephetR2** [linuxmint/cinnamon-spices-desklets#1192]
### Desklet name and maintainer

yfquotes@thegli @thegli

### What would you like to see?

Hi @thegli and thanks for the very useful desklet! 
It would be nice to have the possibility to force refresh to update the ticker manually. I would see that either as a self-standing icon or through clicking anywhere else than one of the active stock ticker symbols. This would help when wanting to unfreeze the ticker, enable users to avoid pinging the Yahoo Finance API every few minutes and set the ticker to update relatively unfrequently, etc.

**Comment by thegli** [comment]
Hi @SonephetR2 

Sounds doable :smiley:
My first idea is to make the "last update timestamp" info at the bottom clickable - would that serve your request?

**Comment by SonephetR2** [comment]
Thanks, that would be a really nice way of implementing my feature request!

Another idea (and perhaps easier to discover by users) could be to serve the option in the right-click menu, after "About… and "Configure…". Anything works for me :)

**Comment by thegli** [comment]
The menu entry looks a tad less convenient (two clicks) :grin: Let's try the one-click option.

**Comment by thegli** [comment]
@SonephetR2
The feature is not enabled by default. The option "Manual update" is located at the first tab in the settings, just below the "Show last update timestamp" option.

Happy Refreshing :rocket:

**Comment by SonephetR2** [comment]
Looks great, thank you so much!! 🚀🚀🚀 I'm sure many other users will use the feature to better monitor their stocks whilst avoiding compulsive stock tracking.
