### ISSUE TITLE
hostcheck@schorschii: Language output in ping command

### ISSUE THREAD

**Issue by minutogit** [linuxmint/cinnamon-spices-desklets#1193]
### Desklet version/Build date

1.2

### Cinnamon version

-

### Distribution

Mint 21.2

### Graphics hardware *and* driver used

-

### Desklet name and maintainer

hostcheck@schorschii @schorschii

### What happened?

Hostcheck Desklet suddenly stopped working.
ping command outputs in German, causing string "0% packet loss" and "100% packet loss" not to be found.
Changed string search to " 0%" " 100%"  (with space) as a temporary fix.

**Request:**
Fix to support ping outputs in multiple languages.

**Comment by schorschii** [comment]
I'm using my system in German too with all language packs installed, but I have no clue how you can get `ping` to print German output. What did you do with your system to achieve this?

**Comment by minutogit** [comment]
That's a good question as to how I achieved that.
I have only installed the language packs and Hostcheck has always worked. But at some point the ping with Hostcheck stopped working and then I looked to see what the problem was and realized that the English text was being parsed, but my ping output was now strangely in German. No idea how that happened.

Here the Screenshot:
https://ibb.co/VQWWdfP

**Comment by minutogit** [comment]
Topic reopened. I must have closed the topic unintentionally.

**Comment by minutogit** [comment]
That's a good question how I achieved that.
I have only installed the language packs and Hostcheck has always worked. But at some point the ping with Hostcheck stopped working and then I looked to see what the problem was and realized that the English text was being parsed, but my ping output was now strangely in German. No idea how that happened.

Here the Screenshot:
https://ibb.co/VQWWdfP

**Comment by claudiux** [comment]
Fixed by #1203
