### ISSUE TITLE
Desklet Bug

### ISSUE THREAD

**Issue by counterpoint** [linuxmint/cinnamon-spices-desklets#1194]
### Desklet version/Build date

Version 1.6 (2024-04-18 13:21:08)

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics]

### Desklet name and maintainer

analog-clock@cobinja.de @cobinja

### What happened?

Count of appointments reflects individual appointments. But it ignores recurring appointments. For example, today I have created a sample appointment, but also have two regular appointments. The desklet shows 1, where it should show 3.

**Comment by Cobinja** [comment]
Wrong desklet. analog-clock@cobinja.de has nothing to do with appointments.
@counterpoint please use the correct desklet you mean.

**Comment by counterpoint** [comment]
My apologies, I didn't spot the drop down for selecting the desklet.
