### ISSUE TITLE
bbcwx@oak-wood.co.uk: Feature Request - Proxy/SOCKS/Tor Support

### ISSUE THREAD

**Issue by universalbyte** [linuxmint/cinnamon-spices-desklets#1204]
### Desklet name and maintainer

bbcwx@oak-wood.co.uk @tipichris

### What would you like to see?

Please add Proxy/SOCKS/Tor Support as it is required for today's Privacy/Anonymity. Thank you.

**Comment by rcalixte** [comment]
@universalbyte I don't see how this feature ties into this desklet. Can you explain further? There are endpoints you can access and manually configure locally.
