### ISSUE TITLE
cpuload@kimse: Cpu load desklet crashes under all conditions

### ISSUE THREAD

**Issue by Alastair-L** [linuxmint/cinnamon-spices-desklets#1205]
### Desklet version/Build date

0.7

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

NVIDIA GeForce RTX 2060 SUPER and nvidia-driver-535

### Desklet name and maintainer

cpuload@kimse @schorschii

### What happened?

Installed desklet, and when I go to activate it cinnamon crashes.

~/.xsession-errors contains the following line:
```
csd-power:1569): CRITICAL **: 20:45:29.169: abs_to_percentage: assertion 'max > min' failed
```

I believe that the error is that somehow cpus_utilization has NaN values in it. I'm not sure why or how though. CPU details:
- AMD Ryzen 7 3700X (16) @ 3.600GHz

Not sure if this is helpful, but here is the contents of /proc/stat (I wasn't able to get a sample from when the NaN values were being displayed though sorry)
```
alastair@alastair-MS-7C37:~/.local/share/cinnamon/desklets/hello-world@alastair$ cat /proc/stat
cpu  82780 65 54694 9320910 4641 0 1518 0 0 0
cpu0 4447 61 2626 584374 290 0 823 0 0 0
cpu1 3319 0 1962 586354 243 0 96 0 0 0
cpu2 4702 0 2436 584509 257 0 48 0 0 0
cpu3 4760 0 2443 584428 247 0 6 0 0 0
cpu4 6316 0 3574 581549 244 0 4 0 0 0
cpu5 6156 1 3528 581830 172 0 0 0 0 0
cpu6 5987 0 3538 581769 375 0 0 0 0 0
cpu7 6178 0 3337 582087 283 0 1 0 0 0
cpu8 4583 0 2404 584547 445 0 12 0 0 0
cpu9 2740 0 10481 574215 145 0 7 0 0 0
cpu10 4852 0 2490 584350 233 0 5 0 0 0
cpu11 4846 1 2731 584076 294 0 53 0 0 0
cpu12 6060 0 3193 582347 264 0 0 0 0 0
cpu13 6295 0 3289 581960 176 0 1 0 0 0
cpu14 5904 0 3371 581415 495 0 142 0 0 0
cpu15 5629 0 3285 581093 470 0 315 0 0 0
intr 12385509 40 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9722 315333 488337 0 0 0 0 0 0 0 0 48 0 0 0 0 0 5424 0 0 0 0 0 0 0 62 43 46 92 29 9 25 9 51 59 64 67 100 111 71 64411 0 719325 2024 0 2646 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 21928933
btime 1719053945
processes 15554
procs_running 1
procs_blocked 0
softirq 3898188 503289 265935 1239 66661 317856 0 8102 1817139 232 917735

```

### Other information

See with the workaround applied:
![image](https://github.com/linuxmint/cinnamon-spices-desklets/assets/32168886/6a3ba837-0255-479b-979b-fa303c007279)

**Comment by schorschii** [comment]
> I wasn't able to get a sample from when the NaN values were being displayed though sorry

This means it happens only sometimes and not always with this CPU?

**Comment by Alastair-L** [comment]
Thank you so much for getting back to me so quickly. To answer your question, I only have one CPU to test on, but it seems to be random which combination of cores it happens to each time.

I think I've found the issue, which is that because the time between when the desklet first registers and the time that it first refreshes is so short, the cpu_total_time does not change between refreshes, and therefore there is a division by zero on the following line:

- https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/cpuload%40kimse/files/cpuload%40kimse/desklet.js#L598

I don't really understand what the algorithm is meant to do on that line to be honest, but I guess it needs to be able to handle when there is no change in cpu_total_time.

![image](https://github.com/linuxmint/cinnamon-spices-desklets/assets/32168886/06cc231c-d7c4-43e6-a889-b0bf4d4294f6)

**Comment by schorschii** [comment]
Interesting, thanks for debugging. Yes, it seems that the time between the first call [here](https://github.com/linuxmint/cinnamon-spices-desklets/blob/7f4f2eda7b1f0465b61a610b9e8c87632ebc8904/cpuload%40kimse/files/cpuload%40kimse/desklet.js#L61) and the second call [here](https://github.com/linuxmint/cinnamon-spices-desklets/blob/7f4f2eda7b1f0465b61a610b9e8c87632ebc8904/cpuload%40kimse/files/cpuload%40kimse/desklet.js#L110) is too short.

Can you please test the version from my [cpu-nan-fix](https://github.com/schorschii/cinnamon-spices-desklets/tree/cpu-nan-fix/cpuload%40kimse/files/cpuload%40kimse) branch? [I removed](https://github.com/schorschii/cinnamon-spices-desklets/commit/fc2eeebf9fa3177d5969733982f732f15b3d0331) one of initial `refreshCpuActivity()` calls. Everything else should work like before.

**Comment by Alastair-L** [comment]
Great! I'l test that after I get home from work tonight (AEST).

Can we also add something in to make sure that this or something like this doesn't cause a crash in the future (like the initial pull request I made?). As a very new user to Linux desktop, I would much much rather a bunch of NaNs than having the desktop environment crash.

**Comment by Alastair-L** [comment]
Just tested your fix now - it works great, all the readings are set to 0% when first loading the desklet which is more intuitive than a bunch of NaNs.
![image](https://github.com/linuxmint/cinnamon-spices-desklets/assets/32168886/4582e3e4-4753-4ce1-9689-2e17f03d7726)

Thank you for all your support, it's been really encouraging as someone who just installed Mint on my PC a week ago.

**Comment by schorschii** [comment]
You're welcome, thanks for reporting :)
The new version is on the way to the official repo, I created a pull request.
