### ISSUE TITLE
quoteOfTheDay@tinnu: percent issue

### ISSUE THREAD

**Issue by Ilis** [linuxmint/cinnamon-spices-desklets#128]
Hi, @JessW !

Since Quotes started to work in common, here it is minor problem:
Quote

> Гений - это 1% вдохновения и 99% пота.
> 		-- Эдисон

displayed as:

> пота.
> 		-- Эдисон

It is a quote by Thomas Edison:

> Genius is one percent inspiration, ninety-nine percent perspiration.

% sign treated as quote delimiter, but only single % sign per line should do.

**Comment by JessW** [comment]
You're right, @Ilis , I will take a look, thank you!

**Comment by Ilis** [comment]
I found out that quotes extracted from file by counting delimiters and parsing it.

Maybe it's easier and better to call `fortune` with file name as a parameter?

**Comment by JessW** [comment]
Yes, that's how it works now, it's not very neat.  That sounds like a great suggestion.  Doing it that way would also solve the problem of the scary red exclamation mark that is displayed for this desklet in the Desklets window, because it currently reads the file with get_file_contents_utf8_sync.  I will give it a try as soon as I get a chance.

I think I initially wanted to allow for a different separator than '%', but that is perhaps not necessary (and currently not implemented).

**Comment by Ilis** [comment]
Well, I tried to use my own file, copied from fortune package and edited to fix some typos, but get error message:

    ilis@deore ~ $ fortune ~/mygen 
    fortune:/home/ilis/mygen not a fortune file or directory
    fortune:/home/ilis/mygen not a fortune file or directory
    No fortunes found

But I found that file must be prepared:

    ilis@deore ~ $ strfile mygen mygen.dat
    "mygen.dat" created
    There were 109 strings
    Longest string: 666 bytes
    Shortest string: 75 bytes

Then it works:

    ilis@deore ~ $ fortune ~/mygen 
    Клевета равнодушна к ничтожествам.
    		— О. Бальзак

**Comment by Ilis** [comment]
By the way, `strfile` has option to change delimiter character :)

**Comment by JessW** [comment]
Yep, I ran into that too! I was thinking of putting instructions for custom
files in the README. That is great that strfile will let you change the
delimiter!

**Comment by JessW** [comment]
Hi @Ilis !  I submitted a fix for this issue that uses your idea of just calling fortune (thank you!) a couple of days ago.  When you get a chance, could  you see if it solves your issue?  You should just be able to update the desklet the regular way, through the Desklets dialog.  Thanks!

**Comment by Ilis** [comment]
Well, @JessW !

Great job!

I clicked desklet 500 times and got fortune with “%” sign :) So, call to `fortune` works. One more thing is to check `fortune` installed when desklet start. I. e. check error code for `fortune -v`. If not zero, then warn user about to install appropriate packages (program and localized fortunes).

And maybe some instructions for using fortunes in user language and custom file?

**Comment by Ilis** [comment]
I've just noticed the number of fortune variants become much more. I saw a lot of fortunes from the same file I didn't seen before. Maybe it was a bug of previous version, or maybe I was unlucky :)

**Comment by JessW** [comment]
I'm glad to hear it works for you too!  It did cross my mind to check if fortune is installed, but then I thought since it's installed by default I wouldn't check.  But maybe that isn't even true for some localizations, and I think you are right, it would just be a better practice to check if it's installed, so I will add it.

Yes!  I have been meaning to add instructions for installing additional fortune-* packages for other languages.

I do have some instructions for custom files in the readme, do you think they are insufficient?  I added info about strfile with this latest update.

**Comment by Ilis** [comment]
Hi, @JessW 

> I do have some instructions for custom files in the readme, do you think they are insufficient? I added info about strfile with this latest update.

Yes, I did see it after I wrote my comment :)

Fortune game can show fortunes from set of files or even all files from given directory. Desklet can show fortunes only from one file, and fortunes becomes a bit annoying. So, my suggestion is give instruction about how to get fortunes from many files. Something like this:

If you want to make your own set of fortunes, copy your favourite fortunes (i. e. `literature`, `love` and `humour`) from `/usr/share/games/fortunes` to home directory, then open terminal and execute following command:

    cat literature love humour > myfortunes && strfile myfortunes

This will create files `myfortunes` and `myfortunes.dat` in your home directory. Then go to desklet settings and choose file `myfortunes` from home directory.

My English is ugly, sorry :)

And all above assumes that somebody read readme and instructions in common :)

**Comment by JessW** [comment]
I do remember you mentioning earlier that allowing multiple input files would be a nice feature, @Ilis :)  I like your instructions, I will work them in to the readme in the next update.  Your English is very understandable, really!

**Comment by Ilis** [comment]
Formally, this issue is closed, bug doesn't exists now. I have button “Close and comment“, but I'm not sure about who should close the issue: issue starter, desklet author, repository owner or whoever?

**Comment by JessW** [comment]
I don't have the button, I think you can close it, or tag one of the report owners?
