### ISSUE TITLE
Yahoo Finance Quotes - API returns 401

### ISSUE THREAD

**Issue by mockturtl** [linuxmint/cinnamon-spices-desklets#1315]
### Desklet version/Build date

0.15.1 (2024-11-11 09:10:31)

### Cinnamon version

6.2.9

### Distribution

LMDE

### Desklet name and maintainer

yfquotes@thegli @thegli

### What happened?

Since the timestamp below, the applet shows "Yahoo Finance service not available!"

Looking Glass:

```
warning t=2024-11-18T23:50:13Z yfquotes@thegli - Error retrieving url 
https://query1.finance.yahoo.com/v7/finance/quote?symbols=^GSPC&crumb=VUhdwwSm6q2. 
Status: 401 Unauthorized
```

### Other information

https://query1.finance.yahoo.com/v7/finance/quote?symbols=^GSPC&crumb=VUhdwwSm6q2

A bit.ly link in the response opens a Google Form explaining the API is discontinued.

> Yahoo Finance | API Feedback
> Again, we’re sorry for the inconvenience, but API-level access to Yahoo Finance quotes data has been disabled.
> Thank you for your feedback.

**Comment by thegli** [comment]
Same happened to me :sweat_smile: 
While I still have to investigate if something changed on the lifetime of the credentials, the 401 situation can be remedied with a restart of Cinnamon (e.g. with keyboard shortcut Ctrl-Alt-Esc), or by removing and re-adding the desklet.
Let me know if this worked for you.
