### ISSUE TITLE
[daysCountdown@KopfDesDaemons] Cannot configure `Days Countdown`

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-desklets#1326]
### Desklet version/Build date

1.0 (2024-11-24 16:54:57)

### Cinnamon version

6.2.9

### Distribution

Mint 22 Cinnamon

### Desklet name and maintainer

daysCountdown@KopfDesDaemons @KopfdesDaemons

### What happened?

I just installed the desklet and added one instance. I then wanted to configure it, but neither the `Configure` icon nor the `Configure...` menu item, when right clicking the desklet, opens a dialog to configure the desklet.

### Other information

The `.xsession-errors` file does not show any error:
```
Gjs-Message: 18:59:27.012: JS LOG: [LookingGlass/info] Installing settings for daysCountdown@KopfDesDaemons
Gjs-Message: 18:59:27.012: JS LOG: [LookingGlass/info] Settings successfully installed for daysCountdown@KopfDesDaemons
Gjs-Message: 18:59:27.019: JS LOG: [LookingGlass/info] Loaded desklet daysCountdown@KopfDesDaemons in 18 ms
```

Restarting cinnamon does not help either.

**Comment by KopfdesDaemons** [comment]
@rcalixte The problem only occurs after your change `"max-instances": "-1".` How can I fix this?

**Comment by rcalixte** [comment]
> @rcalixte The problem only occurs after your change `"max-instances": "-1".` How can I fix this?

I can't seem to duplicate this? Can you share any screenshots?

**Comment by KopfdesDaemons** [comment]
After this change, the settings can no longer be opened at all. With `max-instances": "50"` everything works fine.

Gjs-Message: 20:06:58.867: JS LOG: [LookingGlass/info] Settings successfully installed for daysCountdown@KopfDesDaemons
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 312, in load_instances
    int(instance_id)
ValueError: invalid literal for int() with base 10: 'daysCountdown@KopfDesDaemons'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 594, in <module>
    window = MainWindow(xlet_type, uuid, *sys.argv[3:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 160, in __init__
    self.set_instance(self.instance_info[0])
IndexError: list index out of range
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,

**Comment by rcalixte** [comment]
Hmm, let's try removing that line entirely. There might be a bug in Cinnamon itself. The proper syntax for "no maximums" is supposed to be a value of -1.

**Comment by KopfdesDaemons** [comment]
It works without the line, but I only have one instance at most.

**Comment by rcalixte** [comment]
> It works without the line, but I only have one instance at most.

I'll make a note to see what might have changed that could have impacted this. Assuming it is upstream, other Spices could be impacted as well.

**Comment by sphh** [comment]
I updated the desklet and use it now for tracking two dates. I can confirm, that the configuration is working for both. Thanks!!

And thanks to @rcalixte to pick it up and change the desklet name and maintainer!
