### ISSUE TITLE
[daysCountdown@KopfDesDaemons] %f days remains untranslated

### ISSUE THREAD

**Issue by rinaldus** [linuxmint/cinnamon-spices-desklets#1371]
### Desklet version/Build date

1.0

### Cinnamon version

6.4.2

### Distribution

Manjaro

### Desklet name and maintainer

daysCountdown@KopfDesDaemons @KopfDesDaemons

### What happened?

I pushed a translation of this desklet recently, but "days word" remains untranslated. Look at the screenshot.
![Screenshot_20241216_065221](https://github.com/user-attachments/assets/68eea40b-9ed6-4e99-b7d7-329c2b62f7d3)

I guess, this happens due to this string in the desklet.js. There's no reference to translation in "%f days".
`getDaysString() {
        return _("%f days").format(this.calcDays().toString());
    },`

**Comment by KopfdesDaemons** [comment]
I always test the German translation myself. I had no problems with that. I have now set my system to Russian and the Russian translation also works. See my screenshot.
Please make sure that you have also installed the desklet update.

![Снимок экрана от 2024-12-16 17-28-54](https://github.com/user-attachments/assets/e8ac005b-4970-4bdd-9c84-d9ef4ae92091)

Your translation is here:

```
#. desklet.js:75
#, javascript-format
msgid "%f days"
msgstr "%f дней"
```

**Comment by rinaldus** [comment]
Sorry, I updated desklet, but didn't think that I have to restart Cinnamon to make translation work properly.
