### ISSUE TITLE
Analog Clock doesn't show up in Mint 17.3

### ISSUE THREAD

**Issue by ghardy2k** [linuxmint/cinnamon-spices-desklets#16]
this seems to be a newer version, but doesn't show up in mint 17.3.   the clock is there, but not visible.

**Comment by collinss** [comment]
@ghardy2k please include the applet desklet or extension in the title of the issue, along with a brief description of the issue. It will be impossible to keep track otherwise. Also, you should reference the author in your description so they get notified.

**Comment by ghardy2k** [comment]
analog-clock@cobinja.de - love it, but recently stopped working.  i used to have mint 18, but something kept making my screen blank out, so i went back to 17.3.  this time, the clock stopped working, or at least showing up.  the clock is actually there....i can click it, move it, etc, but it simply isn't visible.

**Comment by Cobinja** [comment]
As the desklet's creator, I'm working on it

**Comment by ghardy2k** [comment]
i wish i knew more about building projects, gtk, and tesitng in linux.  i would love to help out testing and stuff.  but i'm a .net developer, so i really don't know the linux side too well.

**Comment by Cobinja** [comment]
Fixed with https://github.com/linuxmint/cinnamon-spices-desklets/commit/672f3753b0a7997108eca0c4009f9ef75ab59593

**Comment by ghardy2k** [comment]
that did the trick!  you da man!  thanks so much!
