### ISSUE TITLE
simple-system-monitor@ariel: desklet crashes on Cinnamon 3.4

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-desklets#169]
@arielandrade 
Your desklet crashes on Cinnamon 3.4.

It's having problems with 
```
const NMClient = imports.gi.NMClient;
const NetworkManager = imports.gi.NetworkManager;
const GTop = imports.gi.GTop;
```
being in `try-catch-blocks`.

If you remove the try-catch-block the desklet works (if you have the needed packages installed.)
I think it's because of the new js interpreter in Cinnamon 3.4.

Maybe @jaszhix knows more about it.

**Comment by arielandrade** [comment]
Thank you @NikoKrause, I'll check it ASAP
