### ISSUE TITLE
Analog clock not visible in Mint 17.3

### ISSUE THREAD

**Issue by ghardy2k** [linuxmint/cinnamon-spices-desklets#17]
analog-clock@cobinja.de - Analog Clock

in mint 17.3, i can click it, move it, get to settings...but it is not visible on the desktop.

**Comment by Cos-mo** [comment]
Works fine here on Mint 17,3.

Do you have the package gir1.2-rsvg-2.0 installed?

**Comment by Cobinja** [comment]
Duplicate of #16, closed here
