### ISSUE TITLE
CobiAnalogClock : Seconds hand visible on loading when disabled

### ISSUE THREAD

**Issue by DanielCoffey** [linuxmint/cinnamon-spices-desklets#172]
@Cobinja

BUG : The Seconds hand is visible on the clock when starting Mint even when it has been disabled in the desklet settings in a previous session.

Version : 2017-06-13 15:20:02 UTC

Steps to reproduce : 

1. Add Analog Clock to Desktop and select Default theme
2. Right-click the desklet and select Settings
3. Untick "Show Seconds" then click Apply
4. The seconds hand correctly disappears
5. Reboot the Mint desktop (or change the clock face to a different Theme)
6. The Seconds hand is back and is pointing straight up and does not move

Even leaving the desklet until the minute hand next updates does not get rid of the seconds hand at all. You have to go back in and select/deselect Show Seconds again to hide it until the next reboot.

**Comment by NikoKrause** [comment]
Which desklet are you talking about? Add it in the title.

**Comment by NikoKrause** [comment]
Also:
You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/

**Comment by DanielCoffey** [comment]
Cheers - done.
