### ISSUE TITLE
[analog-clock@cobinja.de] Cinnamon crashes when desklet is moved

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/cinnamon-spices-desklets#180]
@cobinja.de

New install of Mint 18.2. Didn't happen on new install of Mint 18.1.

When the clock is moved on the desktop it doesn't take long for Cinnamon to crash. *Doesn't happen with other desklets*.

Kernel: 4.8.0-58-generic x86_64
Desktop: Cinnamon 3.4.4 (Gtk 3.18.9-1ubuntu3.3)

**Don't ask to submit logs, I won't submit them.**

**Comment by Cobinja** [comment]
Sorry, I can't reproduce this.
And since you're obviously unwilling to provide logs: Have a nice day!
