### ISSUE TITLE
clock@schorschii: Smooth seconds hand option wording

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-desklets#20]
@schorschii 
The option `Smooth seconds hand` is not only affecting the seconds hand, but also the minute hand and the hour hand:
The first picture is with smooth option on and the second picture with the smooth option off (approx. same time +-10 seconds)
![screenshot-cinnamon-2017-04-02-145036](https://cloud.githubusercontent.com/assets/8415124/24587409/3bc20f96-17b6-11e7-8475-b80dc217d31e.png)
![screenshot-cinnamon-2017-04-02-145046](https://cloud.githubusercontent.com/assets/8415124/24587411/3d529006-17b6-11e7-90b5-b45ea0aefa19.png)

**Comment by schorschii** [comment]
@NikoKrause Thanks for this hint. I will correct the setting description in the next version.
