### ISSUE TITLE
googleCalendar@javahelps.com unable to retrieve events on calendar name

### ISSUE THREAD

**Issue by abrianceau** [linuxmint/cinnamon-spices-desklets#203]
```
 * Desklet version/Build date 1507314374
 * Cinnamon version 3.4.6
 * Distribution - Debian unstable
 ```

**Notify author of desklet**
@slgobinath

**Issue**
Unable to retrieve events when we set a calendar name.

**Steps to reproduce**
Add a calendar name in settings

**Other information**
I think the problem is that you put calendar's names at the end of the command (I read the function on_calendar_config_changed) instead of the begining :
```
abr@moana:~$ gcalcli --refresh --nocache agenda --nostarted --tsv --calendar "alexandre.brianceau@mycompany.com"
The following options are either no longer valid globally or just plain invalid:
  --calendar
Error: failed to parse start time
abr@moana:~$ gcalcli --refresh --nocache --calendar "alexandre.brianceau@mycompany.com" agenda --nostarted --tsv
2017-10-09	14:30	2017-10-09	16:00	XXXXXXXXXXX
2017-10-10	09:00	2017-10-10	11:00	XXXXXXXXXXX
```

**Comment by slgobinath** [comment]
Hi,
I do use calendars in my system. It is okay to change the order if that fixes your problem but I wonder why you get these problems. May I know your `gcalcli` version?

In my case, it is 3.3.2
```
$ gcalcli --version
gcalcli v3.3.2 (Eric Davis, Brian Hartvigsen)
```

**Comment by abrianceau** [comment]
Hi ! My version :
```
$ gcalcli --version
gcalcli v4.0.0a3 (Eric Davis, Brian Hartvigsen)
```

**Comment by abrianceau** [comment]
Do you need more informations in order to update the code for the new synthax of gcalcli ?

**Comment by slgobinath** [comment]
Hi,
Sorry, I forgot to update you back. I think you have installed `gcalcli` using pip3 (for Python 3). When I use pip3, I couldn't get it installed on my Linux Mint 18.2 machine.

The `gcalcli` available for Python 2 and the version available on Ubuntu repository works without any issues. Further, I remember changing the order with Python 2 version, caused to a similar problem. Could you please try downgrading your `gcalcli`?

**Comment by abrianceau** [comment]
I installed through `apt-get` on Debian Sid. 
```
apt-cache policy gcalcli
gcalcli:
  Installé : 4.0.0~a3-1
  Candidat : 4.0.0~a3-1
 Table de version :
 *** 4.0.0~a3-1 500
        500 http://ftp.fr.debian.org/debian testing/main amd64 Packages
        500 http://ftp.fr.debian.org/debian testing/main i386 Packages
        100 /var/lib/dpkg/status
```
Maybe you should modify your apps for this new version because, sooner or later it will become the standard :)

**Comment by abrianceau** [comment]
I installed throught pip :
`sudo pip install gcalcli`
And now it works (of course). I close the ticket but this bug still exists until you adapt the code to the new syntax.

**Comment by slgobinath** [comment]
Sure.
I am thinking about a native JavaScript way to access Google Calendar and will migrate to that soon.
