### ISSUE TITLE
clock@schorschii: clock looks blurry if scaled

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-desklets#21]
@schorschii 
If you scale the clock it looks blurry.
If you would use vector graphic images (.svg files) this issue would be solved.

**Comment by schorschii** [comment]
@NikoKrause I'm aware of that, the default image is not suitable for scaling (> 1.0). But I wanted to add this possibility if the user uses his own image. A vector graphic as default image will follow in a future version.
