### ISSUE TITLE
clock@schorschii: desklet label not visible

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-desklets#22]
@schorschii:
I don't see no desklet label at all.

**Comment by schorschii** [comment]
Hi @NikoKrause 
desklet labels are only shown if you enable decorations in cinnamon. 
![1](https://cloud.githubusercontent.com/assets/17480795/24623677/88ef143c-18a9-11e7-801e-39cff915d0a4.png)

**Comment by NikoKrause** [comment]
Where can I enable decorations?

**Comment by schorschii** [comment]
@NikoKrause Go to desklet settings > General Settings > Decoration of desklets > Border and header

**Comment by schorschii** [comment]
@NikoKrause Could you please close this issue?
