### ISSUE TITLE
googleCalendar@javahelps.com has Misaligned times

### ISSUE THREAD

**Issue by dzek69** [linuxmint/cinnamon-spices-desklets#222]
```
 * Desklet version/Build date: 2017-11-22 17:27:46 UTC
 * Cinnamon version: Cinnamon 3.4.3
 * Distribution: Mint 18.2
 * Graphics hardware *and* driver used: nVidia GTX950M, nvidia-384.90-0ubuntu0.16.04.2
 * Snippet or attachment of ~/.cinnamon/glass.log: https://pastebin.com/raw/yxsdSXvU
 * Snippet or attachment of ~/.xsession-errors: https://pastebin.com/raw/gEKSjVSZ
 ```

**Notify author of desklet**
@slgobinath

**Issue**
Times displayed on desklet are misaligned, sometimes too much to the left, sometimes too much to the right. But they're not random, some of them are aligned properly and that doesn't seem to be connected with use of regionalized characters or unicode (which would be my first guess).

**Steps to reproduce**
No idea, I guess the best way is to install on the same OS and specs as I have and try to add the same events to the calendar.

**Expected behaviour**
All times should be equally aligned.

**Other information**
Screenshot:
![screenshot-area-2017-12-04-130559](https://user-images.githubusercontent.com/4936805/33552100-00d8ad54-d8f4-11e7-801a-110bb7ce791f.png)

**Comment by pbaudoux** [comment]
I get the same issue. Here's my spec:

```
* Desklet version/Build date: I don't know how to check this, but I installed it
  yesterday so it should be the latest version.
* Cinnamon version: Cinnamon 3.4.6
* Distribution: Ubuntu 17.10
* Graphics hardware *and* driver used: Intel Corporation HD Graphics 520, Intel i915
* Snippet or attachment of ~/.cinnamon/glass.log: https://pastebin.com/y1B0nryg
* Snippet or attachment of ~/.xsession-errors: No such file or directory
```
![calendar](https://user-images.githubusercontent.com/4053475/33804415-858afcf0-dda4-11e7-9409-03c582127dcb.png)

As I get the problem only for one type of event I checked the difference in the .ics:

Buggy event:
```
BEGIN:VEVENT
UID:157425EB12ECC3DD30A20C3674B322F320171211@gehol.ulb.ac.be
DTSTART;TZID=Europe/Brussels:20171211T120000
DTEND;TZID=Europe/Brussels:20171211T140000
DTSTAMP:20171210T110513Z
SUMMARY: Guidances d'anglais
LOCATION: S.P1.1.111
DESCRIPTION: Professeur:  \n Communication: Local : P1.1.111 \n Activité: Appui pédagogique \n Groupes: M-IRELE:2
END:VEVENT
```
Normal event:
```
BEGIN:VEVENT
UID:A54DFF2DE219DACAF099D7A10902E21120171211@gehol.ulb.ac.be
DTSTART;TZID=Europe/Brussels:20171211T100000
DTEND;TZID=Europe/Brussels:20171211T120000
DTSTAMP:20171210T110513Z
SUMMARY: Mobile and wireless networks [ELECH423]
LOCATION: S.C2.223
DESCRIPTION: Professeur: Dricot\, Jean-Michel \n Communication:  \n Activité: Théorie \n Groupes: M-IRELE:2 - Information and Communication Technology Systems
END:VEVENT
```
Hope it helps.

Best regards,
Pierre

**Comment by slgobinath** [comment]
Hi all,
For the moment I am little busy with my research. I will fix this issue once I get some time.

Thanks for reporting it.

**Comment by slgobinath** [comment]
Fixed in https://github.com/linuxmint/cinnamon-spices-desklets/pull/259. Please update the desklet and see whether it has been resolved.

Thanks
