### ISSUE TITLE
stocks@fthuin: Yahoo API shut down, breaking desklet

### ISSUE THREAD

**Issue by ase1590** [linuxmint/cinnamon-spices-desklets#224]
Yahoo has shut down their finance API, breaking this stock ticker desklet. See here: https://www.quora.com/Did-Yahoo-Stock-API-shut-down

A respondent suggests using the Alpha Vantage API: https://www.alphavantage.co/documentation/

**Comment by fthuin** [comment]
You are right, this desklet is not working anymore. It can be removed unless someone comes with a new implementation using AlphaVantage or any other API. If someone already has experience with AlphaVantage, he can modify my existing desklet and becomes the new owner.

**Comment by NikoKrause** [comment]
Hey, if it's broken and you don't want to fix/maintain it anymore, I'm going to delete it.

**Comment by NikoKrause** [comment]
There's a fork now of this desklet: https://cinnamon-spices.linuxmint.com/desklets/view/42
