### ISSUE TITLE
bbcwx@oak-wood.co.uk: Clicking Desklet Should Open PWS

### ISSUE THREAD

**Issue by tomkiti** [linuxmint/cinnamon-spices-desklets#225]
```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json"): 2.10
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.3
 ```

**Notify author of desklet**
@tipichris

**Issue**
When using Weather Underground as a data service and a Personal Weather Station (PWS) as the location, clicking the desklet should go to the PWS, not the city.

**Steps to reproduce**
Select Wunderground as the data service and enter pws:KMDCOLUM3 as the location. Click the desklet. The browser goes to https://www.wunderground.com/weather/us/md/columbia.

**Expected behaviour**
The browser should go to https://www.wunderground.com/weather/us/md/columbia/KMDCOLUM3.

**Comment by tipichris** [comment]
Wunderground's API returns three URLs

forecast_url: http://www.wunderground.com/US/MD/Columbia.html
history_url: http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMDCOLUM3
ob_url: http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.196098,-76.796097

The desklet uses the forecast_url, on the assumption that most users are more interested in the future weather than the past weather. Unfortunately the API does not return a URL for the forecast for the PWS. Obviously in this case it would be relatively trivial to construct the URL you are after, but unfortunately the way in which WU constructs URLs is not consistent across countries, and does not appear to be documented. The structure of URLs for my local PWS of IWARWICK37 differs markedly, for example. The desklet therefore needs to rely on the URLs reported by the API. It's unlikely that this issue will be resolved unless

* WU change their API and start reporting the station URL
* You (or someone) can find a consistent and reliable way to construct the necessary URL from data available to the desklet (essentially the station ID, and the URLs reported by WU's API)
* You can convince me that it makes more sense to use the history URL than the forecast URL, which doesn't appear to be what you're requesting. However, it is only one click from the PWS history to the PWS forecast, and that behaviour appears to be consistent.

**Comment by tomkiti** [comment]
Wow, what a horrible API! I tried everything I could think of, but I agree that there's no easy way to get the PWS URL using the API. Even the 3 URLs that are returned point to 3 different PWSs! The current behaviour is definitely sufficient. Thanks for looking into it.
