### ISSUE TITLE
devTools@scollins- broken

### ISSUE THREAD

**Issue by the-w-e-e-d-i-a-n** [linuxmint/cinnamon-spices-desklets#244]
Sonya 18.2 64
Cinn 3.4.6

error t=2018-01-16T09:19:41Z No JS module 'desklets' found in search path
trace t=2018-01-16T09:19:41Z 
<----------------
@/home/the_weedian/.local/share/cinnamon/desklets/devTools@scollins/desklet.js:23:7
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155:13
Extension@/usr/share/cinnamon/js/ui/extension.js:116:5
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449:25
_onEnabledDeskletsChanged@/usr/share/cinnamon/js/ui/deskletManager.js:203:16
---------------->
error t=2018-01-16T09:19:41Z [Desklet "devTools@scollins"]: Error importing desklet.js from devTools@scollins
error t=2018-01-16T09:19:41Z Could not load desklet devTools@scollins

**Notify author of desklet**
@collinss 

**Issue**

wont load, crashes, disables self, still appears as "updated" with green check in manager...

removal of folder from udr/share/cinnamon/desklets changes nothing... still appears as installed, up to date on "available online" tab... and with a red exclamation in local tab... whether folder is in share or not. i wonder if this is my error, and cinnamon settings need changed?

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by the-w-e-e-d-i-a-n** [comment]
This is LITERALLY my first github post ever... If i violated some rules egregiously, I apologize in advance.

**Comment by collinss** [comment]
Yeah, the imports system changed in 3.6 and it looks like the change is not back-wards compatible with older versions of Cinnamon.

@jaszhix thoughts?

**Comment by jaszhix** [comment]
I forgot about this, sorry. I was going to [submit a PR](https://github.com/jaszhix/cinnamon-spices-desklets/commit/8ec4fc19832cb3fbe5e92579a80f61338e56839a) for this but you said you would take care of it. I can still try to submit it if you'd like, but its not merge-able anymore.

**Comment by the-w-e-e-d-i-a-n** [comment]
...and to think I had JUST found my holy grail of Cinnamon small tweak tools... :/

**Comment by the-w-e-e-d-i-a-n** [comment]
FYI: I just virtualized Manjaro 64bit, (Arch)... with Cinnamon 3.6.6... and it loaded like butter. Don't know if that info helps?

**Comment by collinss** [comment]
It currently works fine in Cinnamon 3.6. You could consider upgrading your system to 18.3. You can do that easily through the update manager. The impact on your system would be minimal and the risk should be pretty low. (I'd still do a system backup just to be safe of course.)

**Comment by collinss** [comment]
@jaszhix I don't recall that conversation now. (Doesn't mean it didn't happen, I've just had a lot going on in my life lately.) If you could pr a solution that works with both versions of Cinnamon, that would be appreciated.

**Comment by the-w-e-e-d-i-a-n** [comment]
Good suggestion!
I'm looking forward to learning more about how to write my own applets/desklets for Cinnamon specifically... It's the desktop I ALWAYS gravitate back to, and I think I'm done jumping around and reinstalling OSes for a bit... Any suggestions on where to start if someone's just a hobby python/css/js person? Or just pour over your guy's code, and then ask to be included? I don't want to waste people's time with stupid questions... I want to study before I try to join this effort, but I want tips from the architects of Cinnamon on where they think I should start... (even if it's just this once, here. :) )

**Comment by collinss** [comment]
Well, nothing beats playing around with an existing applet, but there are some other resources you can use too. Devhelp is a great one. You'll have to install additional -doc packages as well (ie cinnamon-doc for the cinnamon documentation) in there you will find API references and tutorials that will be quite helpful.

**Comment by jaszhix** [comment]
@collinss It looks like you [already patched](https://github.com/linuxmint/cinnamon-spices-desklets/commit/a2c99a5faec81b9e9a3d41cc083d33ff1b134468#diff-4bdf98d6377f07adb946247aa3e6dd0d) it, didn't realize that. I think the issue is imports.desklets is new to 3.6. imports.ui.deskletManager.desklets would work with backwards compatibility and importing from the xlet manager object is how I updated the other spices.

@the-w-e-e-d-i-a-n You can always PR something if you find a bug and have a fix. For me, I just needed a window list with app grouping, saw several bugs, it was unmaintained, so I forked it into icing task manager. Nowadays that's not really necessary because the xlets are hosted on github. If there's an xlet without an author (check info.json), those up are up for grabs. We try to keep those working, but there's a lot of them, and the abandoned xlets often get removed if they're too broken.

**Comment by collinss** [comment]
@jaszhix I think I tried this before and it was breaking for me on master. Which is why I changed it iirc.

**Comment by the-w-e-e-d-i-a-n** [comment]
Awesome guys! I may only have my spare time and limited brain cells, but you've got a new recruit. :)

**Comment by the-w-e-e-d-i-a-n** [comment]
![image](https://user-images.githubusercontent.com/35492043/35067003-7c31900a-fba0-11e7-8918-0ed52566d7f9.png)
