### ISSUE TITLE
[analog-clock@cobinja.de] setting become not accessible after update to Cinnamon 3.6.7 (permission denied) !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-desklets#246]
```
 * Desklet version/Build date: 3.0
 * Cinnamon version 3.6.7
 * Distribution - Fedora Linux 26 X64 bit Cinnamon edition
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 5500

 ```
Hi. When I updated my Cinnamon 3.6.7, then the "setting" of desklet became not accessible. I'm receiving the following notification: " ......... Permission denied"

Please your kind fix.

**Comment by NikoKrause** [comment]
@Cobinja The permissions of the file settings.py are false.

**Comment by Nokia808** [comment]
Hi. I received new update for desklet, but it does not work at all ! Same error is still existing & I can not enter setting of desklet !

In "about" section the following: last modified 2018 - 2 - 10 23.39 UTC

**Comment by NikoKrause** [comment]
Have you restarted Cinnamon after the update?
If not, please do so.

Else uninstall, restart Cinnamon, reinstall.

**Comment by Nokia808** [comment]
Hi. You are correct. After reboot my system (because I read your replay after shut down it), desklet now working O.K & finally I entered to setting without problem & I can know modify it.

Thank you for your kind effort !
