### ISSUE TITLE
[analog-clock@cobinja.de] Cinnamon crashes when adding the desklet to desktop

### ISSUE THREAD

**Issue by SSDMAD** [linuxmint/cinnamon-spices-desklets#249]
Hello, its nice to talk to you. Your desklet is too nice and what i'm looking for. But the only problem Cinnamon got crashed every time i added it to the desktop. After like 5 min, even if i remove it.

>     Desktop: Cinnamon 3.0.7
>     Distro: Linux Mint 18 Sarah

When the desklet installed it shows me a red question mark.
https://forums.linuxmint.com/download/file.php?id=39525

And this is my System Infos.
https://forums.linuxmint.com/download/file.php?id=39526

Is there more info you want me to submit?

**Comment by NikoKrause** [comment]
@Cobinja

**Comment by Cobinja** [comment]
@SSDMAD Can you provide the contents of $HOME/.cinnamon/glass.log and $HOME/.xsession-errors ?

**Comment by SSDMAD** [comment]
Hi @Cobinja , Yeah i will provide them with a pleasure :)
First file **$HOME/.cinnamon/glass.log** have just today log. not the day when the cinnamon crashed.
About file **$HOME/.xsession-errors** have nothing in it about the desklet. 
Did you want me to provide it anyway? or let the cinnamon crash then submit it?

**Comment by Cobinja** [comment]
Please let it crash, then provide both

**Comment by Cobinja** [comment]
Sadly there's no useful info in the logs. Does this still happen?
