### ISSUE TITLE
[betterlock] Can you add option to exclude from "Show notifications' sound effects of Cinnamon" ?

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-desklets#257]
Hi dear.

I'm Fedora user 26 user. This is not a bug, but a feature request.

Currently, if user activate "Sound effects for (Show notifications)" from Cinnamon's sound setting, the betterlock applet's "Notification (if activated) will provoke sound effect each time user change CapsLock/NumLock during writing. This announcing for user, though she/he like sound effects for other notifications .......

I suggest to add new option - if possible - to allow user to select - if she/he like - to exclude notifications of this applet from involved by "sound effect of notification of Cinnamon".  

Best.

**Comment by NikoKrause** [comment]
It's not possible to disable sound effects from the applet itself and only for notifications of this applet.
