### ISSUE TITLE
[betterlock] Add new option "show icon only if key is active"

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-desklets#258]
Hi. This is not a bug. This is a feature request.

I like to chose BOTH indicators (CapsLock & Num Lock). Currently, both icons appear in panel (that for CapsLock & that for NumLock) whether corresponding keys is/are activated or not. If corrsponding key toggled ON then it's icon become white in colour. This is O.K

But there is option - in GNOME version of this applet - to make icons of this applet NOT shown UNLESS corresponding key is toggled ON where it's corresponding icon will appear white in colour. 

It is good to add this option for our Cinnamon applet.

Best

**Comment by NikoKrause** [comment]
Please stop opening issues in the wrong repo.
This repo is for desklets. Betterlock is an applet.
Also stop duplicate your own issues.
You already requested this https://github.com/linuxmint/cinnamon-spices-applets/issues/1297
