### ISSUE TITLE
[googleCalendar@javahelps.com] desklet.js can't be imported - Error when adding desklet to desktop.

### ISSUE THREAD

**Issue by stefancon** [linuxmint/cinnamon-spices-desklets#265]
```
 * Desktop: Cinnamon 3.0.7
 * Distro: Linux Mint 18 Sarah
 ```

I am getting an import error when trying to add the desklet to the desktop. Adding different desklets (e.g. bbcwx@oak-wood.co.uk) works flawlessly, which makes this crash quite confusing.

Following log to **glass.log** seems to be relevant:

> error t=2018-02-23T15:26:59.593Z missing : after property id
> trace t=2018-02-23T15:26:59.593Z 
> <----------------
> Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155
> Extension@/usr/share/cinnamon/js/ui/extension.js:116
> loadExtension@/usr/share/cinnamon/js/ui/extension.js:449
> _onEnabledDeskletsChanged@/usr/share/cinnamon/js/ui/deskletManager.js:203
> ---------------->
> error t=2018-02-23T15:26:59.593Z [Desklet "googleCalendar@javahelps.com"]: Error importing desklet.js from googleCalendar@javahelps.com
> error t=2018-02-23T15:26:59.593Z Could not load desklet googleCalendar@javahelps.com

**.xsession-errors** only shows:
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by NikoKrause** [comment]
@slgobinath

**Comment by slgobinath** [comment]
Hi,
I am unable to produce this problem in my `Linux Mint 18.3` with `Cinnamon 3.6.7`.
I will try this with your version in VM and let you know.

**Comment by slgobinath** [comment]
@NikoKrause I have faced following problems in Cinnamon 3.0.7:
1. Functions must be defined like this:
```
test: function() {

}
```
However, this format was marked as bad practice in last PR check.
2. Default settings values were not initialized. After fixing the above problem, I got `this.bgcolor` undefined in https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/googleCalendar%40javahelps.com/files/googleCalendar%40javahelps.com/desklet.js#L210

Were there any breaking API changes after Cinnamon 3.0.7?

**Comment by NikoKrause** [comment]
Asking expert here: @jaszhix

**Comment by jaszhix** [comment]
Which PR did the linter mark it as bad practice? The eslint configuration might still need some adjusting. I'm not sure what could be causing the undefined typeerror. I know in Cinnamon 3.2 a new API was introduced for the settings binding API, not sure if there would be behavior differences with the old API.

**Comment by slgobinath** [comment]
Hi,
Please check https://github.com/linuxmint/cinnamon-spices-desklets/pull/259 for `Expected method shorthand. (object-shorthand)` style warning.

**Comment by jaszhix** [comment]
Cinnamon 3.0.7 is getting a bit old, you could try find a commit that you know works with it, and 'fork' that into a 3.0.7 directory, in files/UUID/, like [this](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/CinnVIIStarkMenu%40NikoKrause/files/CinnVIIStarkMenu%40NikoKrause) for example. Then move the latest version into a 3.6 directory (or whatever oldest version still works with the desklet). Then add a `cinnamon-versions` property with an array of version strings in metadata.json. Or just add that to metadata.json without forking a 3.0.7 compatible version including the versions that still work in the list, and they should be alerted that the desklet is incompatible with Cinnamon 3.0.7.

**Comment by slgobinath** [comment]
Thanks for your solution @jaszhix.
Considering the effort to maintain multiple versions, I prefer to let this desklet incompatible with Cinnamon 3.0.7.
In addition, I will provide a manual installation guide explaining how to clone and use an older version.
