### ISSUE TITLE
googleCalendar@javahelps.com: Possible bug in layout of event text

### ISSUE THREAD

**Issue by kanchudeep** [linuxmint/cinnamon-spices-desklets#267]
**Notify author of desklet**
@slgobinath 

**Issue**
In the latest version, the spacing between each events of the day seem to have been increased. The previous look was more compact.

The new spaced look has it's own merits, but I personally prefer the compact layout. Would request to add an option to enable/disable compact layout.

**Comment by kanchudeep** [comment]
Sorry, although restarting `cinnamon` did not have any effect of the layout but restarting the system seems to have gone to the default *compact* layout. So probably it was a `bug`. Unfortunately, didn't take any screenshots or logs...

**Comment by slgobinath** [comment]
Hi,
In the previous version, I used single Label and space between two rows were determined by default space between two lines. In the new design, I use separate Label for each row for proper alignment. Therefore now space is determined by default margin between two Labels which may not be same as line space.
Therefore there can be minor differences but if it is too wide, it may be a bug. If it happens again, please share a screenshot.

Thanks

**Comment by kanchudeep** [comment]
It's happened again:

![googlecalendar](https://user-images.githubusercontent.com/30999796/36653611-41e371e2-1adc-11e8-934e-272f9abd44f7.png)

This happened after Cinnamon crash. Relevant entries in `/var/log/syslog`:
```
Feb 26 09:52:50 ------ kernel: [24530.957794] traps: cinnamon[2631] general protection ip:7f74279548f0 sp:7ffde1635dd0 error:0
Feb 26 09:52:50 ------ kernel: [24530.957801]  in libgobject-2.0.so.0.4800.2[7f7427920000+52000]
Feb 26 09:52:52 ------ kernel: [24532.904654] get_apt_cache.p[23336]: segfault at 7f9a16cef018 ip 00007f79b493fad0 sp 00007ffcda976b90 error 4 in libapt-pkg.so.5.0.0[7f79b480a000+16e000]
Feb 26 09:52:55 ------ cinnamon-session[2299]: WARNING: t+24477.04373s: App 'cinnamon.desktop' respawning too quickly
Feb 26 09:52:55 ------ cinnamon-session[2299]: CRITICAL: t+24477.05226s: We failed, but the fail whale is dead. Sorry....
Feb 26 09:52:55 ------ cinnamon-session[2299]: WARNING: t+24477.05266s: Application 'cinnamon.desktop' killed by signal 15
Feb 26 09:52:55 ------ cinnamon-session[2299]: WARNING: t+24477.05270s: App 'cinnamon.desktop' respawning too quickly
```

**Comment by slgobinath** [comment]
Hi,
May I know the theme you use?

**Comment by kanchudeep** [comment]
The default Cinnamon theme (Mint-X)

**Comment by slgobinath** [comment]
Hi,

I have fixed some HiDPI issues which might be the reason for this problem. Could you please try the latest desklet? Please note that you need to install some additional dependencies to get the new desklet work. Check the updated README for more details.
