### ISSUE TITLE
bbcwx@oak-wood.co.uk: various warning messages

### ISSUE THREAD

**Issue by brownsr** [linuxmint/cinnamon-spices-desklets#27]
@tipichris This desklet throws a number of warning messages (found in .xsession-errors):

Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js 3100]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/marknote.js 90]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/marknote.js 631]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/marknote.js 664]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/marknote.js 691]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/marknote.js 1424]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/marknote.js 32]: assignment to undeclared variable marknote
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js 521]: assignment to undeclared variable prop

**Comment by tipichris** [comment]
Just to say I'm not ignoring this, but have a pile of other stuff to do first.

**Comment by NikoKrause** [comment]
Should this be closed now?

@tipichris fyi
You can close issues through PR, if you add closes #27 or fixes #27 in the PR. When the PR gets merged, the issue will be closed.

**Comment by tipichris** [comment]
As far as I know this should now be resolved. But I'm still using Cinnamon 2.6—it should probably be tested by someone with a more up-to-date installation.
