### ISSUE TITLE
simple-system-monitor@ariel and netusage@30yavash.com need to be updated to support new NM library

### ISSUE THREAD

**Issue by coderforlife** [linuxmint/cinnamon-spices-desklets#279]
Distribution: Fedora 27
Author of `simple-system-monitor`: @arielandrade 
`netusage` is unclaimed

Both of these desklets cannot be loaded on Fedora 27 (and possibly future versions of Linux Mint or other distros) due to the move from `NMClient` and `NetworkManager` libraries to `NM`. Attempting to add this applet will cause Cinnamon to continually crash on Fedora 27.

More about the issue is discussed in https://github.com/linuxmint/cinnamon-spices-applets/issues/1616 which talks about it for the applet multicore-sys-monitor@ccadeptic23 and has a fix in PR https://github.com/linuxmint/cinnamon-spices-applets/pull/1646. A similar fix would be required for each of these desklets as well.

This may be related to #223 which mentions the desklet continually crashing on Fedora 26.

**Comment by coderforlife** [comment]
Due to messed up formatting initially I am unsure if the mention of @arielandrade went through so repeating it.

**Comment by arielandrade** [comment]
Hello Jeffrey, I'm sorry but I can't mantain the desklet right now, I'll
donate it so somebody else might fix it.

**Comment by pdcurtis** [comment]
I fixed the same issue in the matching applet vnstat@linuxmint.com to the issue here in  simple-system-monitor@ariel - see https://github.com/linuxmint/cinnamon-spices-applets/commit/33b76b80a3475773e9b3b568e51705fc80832abf 

I can have a look at system-monitor@ariel  if nobody else shows an interest but it may be a while before I can allocate time and it probably needs to be fixed for Cinnamon 3.8

**Comment by pdcurtis** [comment]
I have found the time and hopefully fixed this issue for netusage@30yavash.com and also a few anomalies I found during testing it. 

I could only do partial testing on a LiveUSB of Fedora 27 so any feedback from users would be useful

**Comment by spantaleev** [comment]
I've recently started experiencing this same problem on Archlinux.

**Comment by pdcurtis** [comment]
@spantaleev  Which applet/desklet is causing the problem and what version of cinnamon are you using?

 `netusage@30yavash.com` should have been fixed and I have just had a new version merged which will work better with cinnamon 4.0

@jaszhix has also recently pushed a fix for `simple-system-monitor` for 3.8 see #327

**Comment by spantaleev** [comment]
@pdcurtis, I'm on 4.0.3 and I'm affected by linuxmint/Cinnamon#8050, which rejects loading `simple-system-monitor@ariel`.

**Comment by pdcurtis** [comment]
I will have a quick look to see if the fix @jaszhix has created for these xlets can easily be applied. He will probably want to comment as he has already been working on it and I am busy today.

**Comment by pdcurtis** [comment]
@spantaleev I have had a quick look and at https://github.com/pdcurtis/cinnamon-spices-desklets/tree/simple-system-monitor-1.0.0/simple-system-monitor%40ariel you will find a modified version which might work for you.  It includes 
  * Changes for Cinnamon 4.0 and higher to avoid segfaults when old Network Manager Library is no longer available by using a multiversion with a 4.0 folder in which I have:
    * Commented out all references to NetworkManager
    * Replaced calls to NetworkManager with equivalent calls to NM
    * Changed logError messages to not reference NetworkManager  

I hope you may be prepared to test it as I currently have no way to test under Cinnamon 4.0.x 

If it looks promising I will generate a PR

@jaszhix for your information only - if this works it completes the xlets affected by linuxmint/Cinnamon#8050 apart from   'turbonote@iksws.com.b' which seems to have disapeared

**Comment by jaszhix** [comment]
@pdcurtis Tested it real quick

Cjs-Message: 05:39:17.154: JS LOG: [LookingGlass/error] 
[simple-system-monitor@ariel]: assignment to undeclared variable NMClient_new
[simple-system-monitor@ariel]: Error importing desklet.js from simple-system-monitor@ariel
Cjs-Message: 05:39:17.154: JS LOG: [LookingGlass/trace] 
<----------------
anonymous@/home/jason/.local/share/cinnamon/desklets/simple-system-monitor@ariel/4.0/desklet.js:13:1
createExports@/usr/share/cinnamon/js/misc/fileUtils.js:210:31
requireModule/</<@/usr/share/cinnamon/js/misc/fileUtils.js:288:25
---------------->

`turbonote@iksws.com.b` had a lot of python 2 code that was broken that required a lot of work on top of a python 3 port, so I removed it. Its in git history and tagged as applet removal though, so can always be revived if someone's interested.

**Comment by pdcurtis** [comment]
@jaszhix Thanks, 
Deleted the `let NMClient_new;` without noticing - fixed and pushed.

**Comment by pdcurtis** [comment]
I have tested my latest updates to simple-system-monitor under Cinnamon 4.03 on a LiveUSB pushed it and created a PR

**Comment by spantaleev** [comment]
Thanks @pdcurtis!

Sorry I haven't been able to find time to test this and help you out.. Been on the go lately..
