### ISSUE TITLE
googleCalendar@javahelps.com - Hi DPI display issue

### ISSUE THREAD

**Issue by GreatAnubis** [linuxmint/cinnamon-spices-desklets#281]
**Notify author of desklet**
@slgobinath

**Issue**
However, with Double Scaling - HiDPI - 4K - the text is cut off in the middle of that desklet. 
I can see smth like:
```
Event 1... 10:15 A...
Event 2... 10:35 A...
```

Switching to normal scaling - the text and desklet is smaller but occupies all the area and I can see event names and times properly. 

**Steps to reproduce**
Switch to HiDPI. See event list. 

**Expected behaviour**
Text should not be cut off.

**Comment by coderforlife** [comment]
I can confirm this bug and was going to report it but it was already reported. Seeing that it has been open for this long with no response I can guess nothing is going to happen with it anytime soon.

**Comment by slgobinath** [comment]
Fixed in #342

**Comment by slgobinath** [comment]
Hi @Auerilas,

Please note that this issue has been fixed with the recent PR. You need to install some new dependencies to get the latest desklet to work. Please check the updated installation instructions.

@jaszhix you can close this issue after the confirmation.

Thanks
