### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by johnfa155** [linuxmint/cinnamon-spices-desklets#286]
today when I put my PC on, the usual weather forecast had a large ? and No Data displayed I tried all settings I could think of but nothing altered the problem

**Comment by jaszhix** [comment]
Please check the [guidelines](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/.github/CONTRIBUTING.md) for bug reports, which is also in the [issue template](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/.github/ISSUE_TEMPLATE).

**Comment by johnfa155** [comment]
sorry, I am new to this sand just wanted some help, I don't know how to fill forms in either you can help or not
