### ISSUE TITLE
[calendar@deeppradhan] First day of week setting

### ISSUE THREAD

**Issue by alensiljak** [linuxmint/cinnamon-spices-desklets#295]
```
 * Desklet version/Build date: 1.0, 2018-04-09
 * Cinnamon version: 3.6.7
 * Distribution: OpenSuse Tumbleweed
 * Graphics hardware *and* driver used: irrelevant
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors
 ```

**Notify author of desklet**
@kanchudeep

**Issue**
This is more of a request than a bug report. The month calendar displays weeks with the first day of the week being Sunday. I would appreciate if the setting for the first day was used from Cinnamon (currently set as Monday).

**Steps to reproduce**

**Expected behaviour**
The week display should respect the Cinnamon setting for the first day of the week.

**Other information**

**Comment by kanchudeep** [comment]
Good suggestion!

I'll work to try and add this...

**Comment by MisterY** [comment]
Wonderful, thank you! I love this desklet.

**Comment by bontchev** [comment]
Any chance this ability could be implemented in the official release? It's been nearly a year already. The part of the world that's not the USA is anxiously awaiting it...
