### ISSUE TITLE
Weather Desklet blocks Cinnamon

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon-spices-desklets#312]
The extension locks Cinnamon you need a manual removal Dell estensione....si Please update it for the latest versions

Cinnamon 3.8.3
Fedora 28 x86-64
Intel Haswell-ULT Integrated Graphics Controller
Advanced Micro Devices [AMD/ATI] Mars LE [Radeon HD 8530M / R5 M240]
x11 (X.org 119.6 ) drivers: i915,radeon Resolution: 1366x768@60.00hz
Mesa DRI Intel Haswell Mobile version: 4.5 Mesa 18.0.2

**Comment by icarter09** [comment]
Cinnamon 3.8.8
Linux Mint 19 64bit

@xzj8b3 What exactly is getting locked up on Cinnamon? I just installed the Weather Desklet and not experiencing any issues or Cinnamon locking up.

**Comment by xzj8b3** [comment]
At the moment I don't have Cinnamon installed, but on Fedora 28 x64 it blocked Cinnamon just like I started the desklet

**Comment by icarter09** [comment]
@xzj8b3 If you ever install Cinnamon again, can you double check if the Weather Desklet is still causing you problems? We'll update the ticket accordingly with your feedback. Thanks!

**Comment by xzj8b3** [comment]
![Uploading P_20180729_142512_vHDR_Auto.jpg…]()

@icarter09 The image clearly shows how Cinnamon crashes when loading the extension on Fedora 28 x64 with open driver!!!

**Comment by leigh123linux** [comment]
Works fine here using F29 x86_64.

**Comment by jaszhix** [comment]
@xzj8b3 Do you have an ~/.xsession-errors file? If so please attach it here.

**Comment by xzj8b3** [comment]
@jaszhix In which folder is the file. xsession-Errors I try to see!!!!

**Comment by jaszhix** [comment]
@xzj8b3 It would be in your home folder if you have it.

**Comment by xzj8b3** [comment]
@jaszhix Of course I do, but there will always be problems if they are updated every 4 months when it goes well!!!!

**Comment by jaszhix** [comment]
@xzj8b3 I don't know what that means, but you still didn't provide any logs.

**Comment by xzj8b3** [comment]
I have no xsession-error registers to provide
