### ISSUE TITLE
Top does not work on recent truths of Cinnamon

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon-spices-desklets#314]
Top does not work on recent truths of Cinnamon, please make it compatible with Fedora 28 x64 so that they can also use other users
Cinnamon 3.8.3 
Fedora x86-64
Intel Haswell-ULT Integrated Graphics Controller
 Advanced Micro Devices [AMD/ATI] Mars LE [Radeon HD 8530M / R5 M240]
 x11 (X.org 119.6 ) drivers: i915,radeon Resolution: 1366x768@60.00hz
 renderer: Mesa DRI Intel Haswell Mobile version: 4.5 Mesa 18.0.2

**Comment by leigh123linux** [comment]
@RyanNerd  It works fine on fedora after editing ~/.local/share/cinnamon/desklets/top@ryannerd/metadata.json and adding 3.8 version

```
{
    "last-edited": 1525245396,
    "cinnamon-version": [
        "3.4",
        "3.6",
        "3.8"
    ],
    "description": "A desklet that displays top process info",
    "name": "Top",
    "prevent-decorations": true,
    "uuid": "top@ryannerd"
}
```

![screenshot from 2018-06-09 11-30-10](https://user-images.githubusercontent.com/1299302/41190543-a5afdea2-6bd8-11e8-8d76-936052f0e63f.jpg)

**Comment by xzj8b3** [comment]
[image: Schermata del 2018-06-09 15-02-55.png]
​

Unfortunately I do not have logs because it does not cause errors, it does
not work and just on Gnome 3.8.3 which indicates that the extension is not
compatible!!!!



Seguimi su Facebook <https://www.facebook.com/IvanDeFelice>  Seguimi su
Twitter <https://twitter.com/xzj8b3>  Seguimi su Istagram
<https://www.instagram.com/ivan_e_toby/> Seguimi su Pinterest
<https://it.pinterest.com/Ivan_e_Toby/>

                            Seguimi su Google +
<https://plus.google.com/+IvanDeFelice>     Segui Gruppo:
Tech.News.&.Tricks.Style
<https://www.facebook.com/groups/Tech.News.e.Tricks.Style/>


Il giorno sab 9 giu 2018 alle ore 12:31 Leigh Scott <
notifications@github.com> ha scritto:

**Comment by xzj8b3** [comment]
So it was updated??? Really thank you..
