### ISSUE TITLE
#205 quoteOfTheDay@tinnu: copy in right-click-menu doesnt work

### ISSUE THREAD

**Issue by InfLagranty** [linuxmint/cinnamon-spices-desklets#317]
```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version 3.8.4-1 (cinnamon --version)
 * Distribution - (Arch)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@

**Issue**
title is self-expanatory, i guess.. i cant even get some usefull logs out of looking.glass / melange

**Steps to reproduce**

**Expected behaviour**

**Other information**
good idea anyway

**Comment by jaszhix** [comment]
@JessW

**Comment by JessW** [comment]
Thanks, @jaszhix!

This works for me on Cinnamon 3.0.7, so I will take a look and try to see when it stopped working.  It might be awhile though, I'm sorry to say!

**Comment by JessW** [comment]
Hi @InfLagranty , I just submitted a pull request that fixes this bug. I'm not quite sure how long that change takes to get pushed out, but if you update Quote of the Day in a day or two, and it's still broken, let me know!

**Comment by JessW** [comment]
@jaszhix Could you close this issue (I don't see a way to do it myself), since I've fixed it now?  Also, I'm not sure who to tag for these kinds of requests, I'm sorry if it's not you!
