### ISSUE TITLE
yfquotes@thegli - Not able to pull Dow (DJIA) or any of the other major indexes. 

### ISSUE THREAD

**Issue by pgwalsh** [linuxmint/cinnamon-spices-desklets#320]
```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jaszhix** [comment]
@thegli

**Comment by thegli** [comment]
@pgwalsh Which quote symbols did you try?

**Comment by pgwalsh** [comment]
Sorry, you're right. For some reason I had found another page with different symbols and I'm used to using the widget on OS X, which works differently. Apologies for the bother.
