### ISSUE TITLE
[diskspace@schorschii] HiDPI display issue

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/cinnamon-spices-desklets#324]
```
 * Desklet version 1.1
 * Cinnamon version 3.8.8
 * Distribution - Mint 19
 ```

**Notify author of desklet**

@schorschii 

**Issue**

Fonts are overlapping on HiDPI displays.

![image](https://user-images.githubusercontent.com/1702193/43035194-75042568-8ceb-11e8-86d2-d11c97e39723.png)

**Comment by Redsandro** [comment]
Fixed in PR - untested on Low DPI

Screenshot of fix:

![image](https://user-images.githubusercontent.com/1702193/43035211-f74197d6-8ceb-11e8-8333-0aebb24daeea.png)

**Comment by schorschii** [comment]
@Redsandro 
Thanks! Also working great on Low DPI.

**Comment by Redsandro** [comment]
Thanks for testing! Can you let the folks in the PR (#325) know?
