### ISSUE TITLE
Localization fail

### ISSUE THREAD

**Issue by ArtHome12** [linuxmint/cinnamon-spices-desklets#329]
![2018 07 31 screenshot](https://user-images.githubusercontent.com/10239307/43462296-ed66779c-94ff-11e8-9afa-1fad2526e851.png)

```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json") 2018 05 11
 * Cinnamon version (cinnamon --version) Cinnamon 3.8.8
 * Distribution -  Mint

 ```

**Notify author of desklet**
@jaszhix 

**Issue**
Wrong month name in russian locale

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by RyanNerd** [comment]
@ArtHome12 You should include the UUID of the desklet in the issue title. Also you should notify the author of the desklet. 
I think the desklet you are referring to is: simple-system-monitor@ariel and the author is @arielandrade

**Comment by NikoKrause** [comment]
This issue seems to be very similar: https://github.com/linuxmint/cinnamon-spices-applets/issues/238

**Comment by ArtHome12** [comment]
Yes, it's the same, tnx!
