### ISSUE TITLE
top@ryannerd : add language support (starting with Spanish) [Help Wanted]

### ISSUE THREAD

**Issue by RyanNerd** [linuxmint/cinnamon-spices-desklets#332]
**Issue**
I am the creator of the `top` Desklet and I am looking for someone who can give me some guidence on how to build .po files and how I would go about testing the translations.

I have a co-worker who is fluent in Spanish and English, and would like to start with that language. But if anyone else wants to throw their hat into the ring for translations I'd love any help.

I'm going to start by looking at other desklets that have localization working to try and figure this out
* Any suggestions for a good one to use as a _template_?
* Any online resources or guides that I can look into on how to do this?
* What do I do as the first step?

**Comment by NikoKrause** [comment]
There's a script in the repo: https://github.com/linuxmint/cinnamon-spices-applets#translations

Here's also a basic tutorial: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/19
