### ISSUE TITLE
googleCalendar@javahelps.com : CalDAV support

### ISSUE THREAD

**Issue by spookylukey** [linuxmint/cinnamon-spices-desklets#358]
I'm interested in adding support for CalDAV calendars, such as those provided by fastmail.fm and many other providers. I could probably program this pretty easily in Python, or Javascript if that would be better.

@slgobinath Would this be accepted? If so, how should it work in terms of interface? I could do it as an external script that has to be configured similar to how gcalcli works. Otherwise there would need to be UI for configuring the CalDAV parameters.

**Comment by slgobinath** [comment]
Hi,
I +1 this but we may need to change the desklet name later.
However, please wait until I fix all the issues in #342 and getting it merged because this PR replaces gcalcli by a Python script and the communication format is defined to JSON. It will give you a nice API (how you pass events to the desklet) to interact with the desklet.

**Comment by spookylukey** [comment]
Great, thanks so much for the feedback. Until #342 is done I'll just work on a script that can generate an agenda from a CalDAV server, without thinking about integration with the desklet.

**Comment by stefan123t** [comment]
Hi, @slgobinath thanks for the current googlecalendar desklet. I only use owncloud/nextcloud caldav API on my own host, therefor +1 on the suggestion of @spookylukey. 

The official gnome-calendar application (I have calendar 3.28.2 on linux mint 19.1 tina at the moment) uses libical3 as a backend. This readily supports Google, Nextcloud/Owncloud and MS Exchange as backends under Linux.
* https://github.com/libical/libical

There are also icalender and icalevents for Python available, the latter probably fitting your requirement for an API to retrieve events for a specific date.
* https://pypi.org/project/icalendar
* https://github.com/irgangla/icalevents

Only thing I am still missing is getting the agenda for the day, week and month displayed on the desktop =^) Thanks for your efforts in this direction.

Kind regards,
Stefan

**Comment by dejalavidavolar** [comment]
> Great, thanks so much for the feedback. Until #342 is done I'll just work on a script that can generate an agenda from a CalDAV server, without thinking about integration with the desklet.

Hi! I hope u are well. Any news about this? I'm interested too on CalDAV integration, because I don't use Google Services.
