### ISSUE TITLE
How to run a command, and read it's output?

### ISSUE THREAD

**Issue by thegergo02** [linuxmint/cinnamon-spices-desklets#368]
(I can't find any documentation, I don't know where to ask questions so I came here.)
I would like to use this to read curl's output. Can somebody link to a documentation?
Thanks.

**Comment by jaszhix** [comment]
The utilities in cinnamon currently don't have an easy way to read stdout, but you could use a function like [this one](https://github.com/linuxmint/cinnamon-spices-applets/blob/07449f8bc6e32218be2fa9c0f532344df4efa27b/IcingWindowSaver%40json/files/IcingWindowSaver%40json/3.6/applet.js#L20). There's a [PR open](https://github.com/linuxmint/Cinnamon/pull/8130) in Cinnamon that adds a variant of this.

**Comment by thegergo02** [comment]
I found another solution to my problem, I used Soup for my get request. Thanks for your help!
