### ISSUE TITLE
battery@schorschii: more than 100%

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-desklets#37]
Look at the screenshot. I'm using Linux Mint 17.3 Cinnamon 2.8.8

@schorschii 

![screenshot-area-2017-04-25-165640](https://cloud.githubusercontent.com/assets/8415124/25392202/4e9a6382-29d8-11e7-8d74-3843849ea88a.png)

**Comment by NikoKrause** [comment]
@schorschii 
And another one:
![screenshot-area-2017-04-25-165640](https://cloud.githubusercontent.com/assets/8415124/25392285/92489c48-29d8-11e7-83f9-e79692099c6b.png)

**Comment by schorschii** [comment]
Could you please provide the content of /sys/class/power_supply/BAT1/capacity? (BAT1 could also be BAT0 or CMB1)
Are you using the newest version (released 3 days ago)?

**Comment by NikoKrause** [comment]
I refreshed the list. It's the newest version. It only happens, when the battery is 100%.

It's BAT0 and the content is `448`.

**Comment by schorschii** [comment]
Thanks. I guess that **charge_now** is higher than **charge_full_design** and **capacity** is calculated by these values. So I have to calculate the capacity myself using **charge_now** and **charge_full**.
Could you please provide all these values when the battery is at 100%?

**Comment by NikoKrause** [comment]
How do I do this?

**Comment by schorschii** [comment]
The mentioned files are also in this directory: /sys/class/power_supply/BAT0 beside the capacity file

**Comment by NikoKrause** [comment]
charge_now: 8739000
charge_full: 1948000
charge_full_design: 8739000
capacity: 448

**Comment by schorschii** [comment]
Great. I'm going to release a fix for that soon.

**Comment by NikoKrause** [comment]
@schorschii 
A quick sidenote. I just translate your desklet. There's this line in the settings-schema
```
"description": "Settings for battery@schorschii   (Version 2.4)"
```
That's a nightmare for a translator. The problem is, that if you change the version number, it's a whole new string to translate. Over and over again.

I'd recommend to add
```
"version": "2.4"
```
in the metadata.json instead. It'll be shown in the "About..." Dialog

**Comment by schorschii** [comment]
Ooops. Didn't know that. I'll improve that.

**Comment by NikoKrause** [comment]
Thanks! It works now.
