### ISSUE TITLE
My for loops don't work

### ISSUE THREAD

**Issue by thegergo02** [linuxmint/cinnamon-spices-desklets#372]
I try to loop through an array, or just write out numbers, but my loops don't run.
Example: `
for (i = 0; i < 5; i++) {
            global.log(i);
        }
`

**Comment by thegergo02** [comment]
I run them at setupUI(), if it makes a difference.

**Comment by jaszhix** [comment]
Extensions run in strict mode, so variables need to be declared. Are you checking ~/.xsession-errors or looking glass log (Alt + L)? You would see: `assignment to undeclared variable i`. Correct syntax:

`for (let i = 0; i < 5; i++) { global.log(i); }` 

I recommend installing an eslint extension for the editor you're using, it helps catch things like this.
