### ISSUE TITLE
googleCalendar@javahelps.com : Won't start anymore

### ISSUE THREAD

**Issue by franckgaga** [linuxmint/cinnamon-spices-desklets#384]
```
 * Desklet version/Build date 2019-01-08, 09:27 UTC
 * Cinnamon version 4.0.9
 * Distribution Mint 19.1
 * Graphics hardware Intel Corporation HD Graphics 520
 * Snippet or attachment of ~/.xsession-errors
Cjs-Message: 16:26:22.165: JS WARNING: [/home/francis/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 101]: test for equality (==) mistyped as assignment (=)?
Cjs-Message: 16:26:22.189: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 30 ms
Cjs-Message: 16:26:22.191: JS WARNING: [/home/francis/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 27]: reference to undefined property "-1"
Cjs-Message: 16:26:22.207: JS LOG: [LookingGlass/info] Loaded desklet googleCalendar@javahelps.com in 18 ms

 ```

**Notify author of desklet**
@slgobinath 

**Issue**
The desklet won't load at all running on the Mint 19.1 cinnamon 4.0.9

**Steps to reproduce**
With the last version of the desklet, add it to your desktop and issue is printed

**Expected behaviour**
The desklet should load.

**Other information**

**Comment by slgobinath** [comment]
Hi,

Warnings in `xdate.js` are known and you can ignore them.

Could you please execute the Python script and see if it prints your Calendar events?
```
cd ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py
python3 google_calendar.py
```

**Comment by franckgaga** [comment]
It won't run. The printed traceback is
`$ python3 google_calendar.py
Traceback (most recent call last):
  File "google_calendar.py", line 29, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'`

**Comment by franckgaga** [comment]
Yep and two other modules were missing. It now works by installing manually these 3 modules :
- `python3-dateutil`
- `python3-oauth2client`
- `python3-googleapi`

Thanks !
