### ISSUE TITLE
googleCalendar@javahelps.com: still won't start (LMDE)

### ISSUE THREAD

**Issue by mockturtl** [linuxmint/cinnamon-spices-desklets#387]
```txt
 * Desklet version/Build date 1547763812 (GMT: Thursday, January 17, 2019 10:23:32 PM)
 * Cinnamon version 4.0.9
 * Distribution - LMDE 3
 ```

@slgobinath 

**Issue**

I was experiencing #384, but after installing the missing dependencies (#385) and updating, the desklet still won't start.  

Here is the output of `google_calendar.py`:

```sh
~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py $ python3 google_calendar.py
Traceback (most recent call last):
  File "google_calendar.py", line 139, in <module>
    main(sys.argv)
  File "google_calendar.py", line 95, in main
    current_time = datetime.now().astimezone()
ValueError: astimezone() cannot be applied to a naive datetime
```

My problem [seems to be](https://stackoverflow.com/questions/12626045/pytz-and-astimezone-cannot-be-applied-to-a-naive-datetime#comment86631711_12626045) due to a change in `python3` minor versions:

> Since version 3.6, `astimezone` works with naive (timezone unaware) datetime... on lower version (<=3.5), timezone unaware datetime has to [call] `pytz.localize`

Debian stable, Ubuntu 16.04: [3.5](https://packages.debian.org/stretch/python3)
Ubuntu 18.04: [3.6](https://packages.ubuntu.com/search?keywords=python3)

**Other information**

I don't know what's good or idiomatic python.  [This](https://stackoverflow.com/questions/4563272/convert-a-python-utc-datetime-to-a-local-datetime-using-only-python-standard-lib) fixes it for me with no extra dependencies; PR incoming.

**Comment by slgobinath** [comment]
Hi,

I have tested this code in my system with the following code.

```python
from datetime import datetime, timezone

t1 = datetime.now().astimezone()
t2 = datetime.now().replace(tzinfo=timezone.utc).astimezone()
t3 = datetime.now(timezone.utc).astimezone()

print(t1)	# 2019-01-21 10:16:51.533650-05:00 - Correct time
print(t2)	# 2019-01-21 05:16:51.533660-05:00
print(t3)	# 2019-01-21 10:16:51.533667-05:00 - Correct time
```
Can you try `datetime.now(timezone.utc).astimezone()` and see if it works.

Thanks

**Comment by mockturtl** [comment]
Yes, `t2` and `t3` both print correctly for me.  I've updated #388 accordingly.
