### ISSUE TITLE
deskNote@BrainAxe : allow multiple instances

### ISSUE THREAD

**Issue by flaviojs** [linuxmint/cinnamon-spices-desklets#395]
This issue is a feature request... I'm using deskNote@BrainAxe and I want to place multiple notes on my desktop.

Changes needed (I'm using Cinnamon 3.0.7):

1) fix the instance id of the settings (`this.instance_id` should be `desklet_id`)
https://github.com/linuxmint/cinnamon-spices-desklets/blob/5b9c23d901512611628b1d9166fa0d1bd8aaa4f0/deskNote%40BrainAxe/files/deskNote%40BrainAxe/desklet.js#L35

2) add "max-instances" to metadata.json (maybe set it to 10?)

**Comment by flaviojs** [comment]
@BrainAxe (poking the author in case he was not notified)

On another note, you can add newlines directly after changing  the setting type from "entry" to "textview" ([available since 1.9.2?](https://github.com/linuxmint/Cinnamon/commit/7e57d3191c2b9e3d66cd01fae6209bfe94c95f55)), so you would not need to use `%%` for newlines anymore.

The setting type is easy to miss since the [online docs](http://developer.linuxmint.com/reference/git/cinnamon-tutorials/xlet-settings-ref.html) do not have it. (cinnamon-docs has it but the search in devhelp isn't good enough, I wish online docs were auto-updated with each release...)

**Comment by BrainAxe** [comment]
Thanks @flaviojs for the information. I am thinking of changing the setting type to "textview". ok?

**Comment by flaviojs** [comment]
Nice, don't forget to update the po folder. (msgid "Note: (use %% for newline)" changed to "Note:")
