### ISSUE TITLE
googleCalendar@javahelps.com : does NOT show events of calendars that are identified by an EMAIL address

### ISSUE THREAD

**Issue by Nigel-727** [linuxmint/cinnamon-spices-desklets#398]
```
 * Desklet version/Build date ("Last modified: 2019-01-22 23:18 UTC")
 * Cinnamon version: Cinnamon 4.0.9
 * Distribution: Mint 19.1


 ```

**Notify author of desklet**
@slgobinath

**Issue**
I first wrote about the issue here 
    https://cinnamon-spices.linuxmint.com/desklets/view/35
under the name "Zoli", on February 19, 2019.

Here are the details:

$ gcalcli list
* CORRECTLY gives a list of all the calendars I have access to:
     Authentication successful.
             Access  Title
             ------  -----
     freeBusyReader  my_friend_susy@gmail.com
              owner  rejtelyek
              owner  elmaradt események
              owner  könyvtár
              owner  my calendar
              owner  (evfordulo [friend])
              owner  anniversaries
             reader  my_friend_rose@gmail.com
             reader  Ünnepek
             reader  XY Facebook-evens
             reader  My_name Facebook-events

$gcalcli agenda
* CORRECTLY lists all events of the above calendars

BUT:
    (as you can see, there are two items in the output of "gcalcli list" 
    that consist of an email address--friends of mine who share their calendars with me, 
    the events of which I can see among mine, for example 
    when Google Calendar is opened in _a web browser_)
    The desklet, however, 
    _does NOT show events of calendars that are identified by an EMAIL address_...
    What is more, its behavior gets unpredicable in those cases... I mean, it's like it 
    STOPs operating normally whenever an email address is included 
    in the comma-separated list of calendars--it doesn't refresh events any longer, for example.

**Steps to reproduce**
   In the comma-separated list of calendar names, include an email address 
   (as the identifier of a calendar that is shared with me by someone else).

**Expected behaviour**
   The desklet should show the events of that shared calendar as well.

**Other information**

**Comment by slgobinath** [comment]
Hi,

Thanks for opening this issue. A bug which **may** cause this issue has been fixed in #397. Once the PR is merged, we can work on this issue.

**Comment by slgobinath** [comment]
Hi,

Please update the desklet and check if it is working or not. If not, please foloow these steps and let me know the result:

1. Open the configuration dialog and enter the following client secret and id:

Client id: `232867676714.apps.googleusercontent.com`
Client secret: `3tZSxItw6_VnZMezQwC8lUqy`

2. Remove the calendar.dat using this command:
```
rm ~/.cinnamon/configs/googleCalendar@javahelps.com/calendar.dat
```

3. Just click on the desklet (or you can remove and add it) to reload events. It will ask your permission to access Google Calendar but the name appeared in the browser will be `gcalcli`.
Give access and see the result.

**Comment by slgobinath** [comment]
Hi @Nigel-727,

Any updates?

**Comment by Nigel-727** [comment]
I will be at my laptop next time on Monday evening at earliest.

Gobinath <notifications@github.com> ezt írta (időpont: 2019. febr. 23.,
Szo, 14:11):

**Comment by slgobinath** [comment]
Sounds good

**Comment by Nigel-727** [comment]
> Hi @Nigel-727,
> 
> Any updates?

Now it works! :+1:

**Comment by slgobinath** [comment]
Hi,

It means something wrong with the permissions I acquire. I will analyze the permissions required by `gcalcli` and update the desklet.

However, there is nothing wrong with using gcalcli authentication. So just enjoy the desklet :-)

**Comment by Nigel-727** [comment]
[offtopic] BTW, is there a way to display not only events but reminders and tasks as well? (like in a web browser) i extensively use them.

**Comment by slgobinath** [comment]
Hi,
Currently, the desklet does not support reminders. I will consider this as a feature request.
Once I get some time, I will work on this.

**Comment by slgobinath** [comment]
Hi,
I would like to see the impact of writable permission in retrieving events. Could you please help me to test the code in your system?

**NOTE: You don't need to modify the desklet configuration for this test.**

1. Open the `~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py` in a text editor and remove the `.readonly` in line number 55.

The original code:
```python
def flow_from_clientsecrets(client_id, client_secret, redirect_uri=None, login_hint=None):
    scope = "https://www.googleapis.com/auth/calendar.readonly"
    ...
```

The code after modification:
```python
def flow_from_clientsecrets(client_id, client_secret, redirect_uri=None, login_hint=None):
    scope = "https://www.googleapis.com/auth/calendar"
    ...
```

2. Delete the calendar.dat
```
rm ~/.cinnamon/configs/googleCalendar@javahelps.com/calendar.dat
```

3. Save the `google_calendar.py` file and run it.

```
python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py
```

It will ask you to authenticate the desklet with read and write permissions and will print your events in the console. Please let me know the result.

Regardless of the output, the desklet should work with gcalcli authentication. So you can either revert the changes or leave the code as you have modified.

Thanks in advance.

**Comment by Nigel-727** [comment]
I did as you asked. At the end, I saw a JSON(!?) list of the events. Then I wrote:
$ python3 google_calendar.py --list-calendars
That gave a list of _all_ the calendars that I have plus _that is shared with me_. :) :+1: 
That's what you were asking in "please let me know the result?"

BTW, is there a dedicated place for feature requests? Because one would be: It is hard to tell events of one calendar from the other, with the only clue being a small colored circle before the event name. (It is especially striking when you'r using decreased font sizes in order to have enough room for display.) For whomever has a dozen calendars of their own, like I have, the ability to differentiate between them is crucial. (Maybe using the event color in the text itself would help...!?)

**Comment by slgobinath** [comment]
Great! I will include the fix in my next commit.

> BTW, is there a dedicated place for feature requests?

You can open a GitHub issue notifying the author. However, no need for the features you already asked:
- Change event color based on Calendar (It will be the next feature)
- Reminders and Tasks (I will start with Tasks)

**Comment by slgobinath** [comment]
BTW thank you very much for your help :-)
