### ISSUE TITLE
googleCalendar@javahelps.com: something went wrong

### ISSUE THREAD

**Issue by BabloP** [linuxmint/cinnamon-spices-desklets#406]
Kernel: 4.15.0-45-generic x86_64 bits: 64 compiler: gcc 
           v: 7.3.0 Desktop: Cinnamon 4.0.9 wm: muffin dm: LightDM Distro: Linux Mint 19.1 Tessa 
           base: Ubuntu 18.04 bionic 
desktop application error "something went wrong googleCalendar@javahelps.com" (desktop)
pip3 install oauth2client
**Requirement already satisfied: oauth2client in ./anaconda3/lib/python3.7/site-packages (4.1.3)**
Looks like anaconda messes up ?
When run on command line 
**python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py --list-calendars**
Everything works, but the desktop application does not work, ... javahelps ... error

**Comment by slgobinath** [comment]
Hi,
Do you get the JSON list of events in the terminal when you run:
```
python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py
```

**Comment by Symilds** [comment]
> Hi,
> Do you get the JSON list of events in the terminal when you run:
> 
> ```
> python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py
> ```

I have the same issue as OP, and when I run the above, i get no output, no errors. 
--list calenders lists everything fine though.

**Comment by zip9** [comment]
I too have the same symptom as Symilds (empty json output), but at times the calendar shows on my desktop. The config must be set at 2 days. I also have the weather desklet, and notice the font on the weather desklet is affected  when adding calendar desklet. After having the calendar desklet appear, it rarely updates on it's own, and will not update when clicked.

**Comment by Symilds** [comment]
I seem to have fixed my issue by manually entering each calendar name, one at a time until I found out which one was causing issues.

**Comment by zip9** [comment]
Thanks for the comment Symilds, I had created calendars on a website - and removing those fixed my issue. Pulled the data, created csv files and imported into Google calendar on Firefox. Would not work on Chrome, but Firefox had no problem...and now all events show. Still have that very attractive shadow (weather desklet fonts) when using calendar, but no issues.
