### ISSUE TITLE
Gulp task doesn't reload the desklet

### ISSUE THREAD

**Issue by f-istvan** [linuxmint/cinnamon-spices-desklets#408]
When I run the gulp watcher as specified in the documentation everything looks good. On saving  `desklet.js` the file is copied to `~/.local/share/cinnamon/desklets/hello@fistvan/desklet.js` and Melange logs the following:
```
info t=2019-03-12T23:46:20Z my log entry
info t=2019-03-12T23:46:19Z Loaded desklet hello@fistvan in 85 ms
```
The desklet also blinks when it reloads.

However, when I change something in `desklet.js` e.g.: `my log entry` to `your log entry` I still see the same log message `my log entry`.
Again the file is replaced (I checked with `cat ~/.local/share/cinnamon/desklets/hello@fistvan/desklet.js`) and the desklet looks reloaded but no change in logs. I have to restart cinnamon to see the new log message. The log is just an example. I can't see any changes I make.

Here is some info on my system:

```
cat /etc/linuxmint/info
RELEASE=18.3
CODENAME=sylvia
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18.3 Sylvia"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_sylvia_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_sylvia_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18.3 Cinnamon 64-bit
```

Could you please help me to find out what I miss?
Thank you.

**Comment by jaszhix** [comment]
Cinnamon 3.6 has a regression where extensions cannot reload. This was fixed in Cinnamon 3.8.
