### ISSUE TITLE
simple-system-monitor@ariel: 'something went wrong while loading'

### ISSUE THREAD

**Issue by Some-Chords** [linuxmint/cinnamon-spices-desklets#414]
@arielandrade 

 * Version 1.0.0
 * Cinnamon 3.6.6
 * Mint 18.3
 * amd64-microcode, Version 3.20180524.1~ubuntu0.16.04.2

Glass.log:
error t=2019-03-23T22:58:08.985Z Could not load desklet simple-system-monitor@ariel
error t=2019-03-23T23:08:18.653Z No JS module 'simple-system-monitor@ariel' found in search path
https://pastebin.com/w6WfL4bT

.xsession-errors
https://pastebin.com/rwQQVjwL

Not sure what else to add. Tried installing it the standard way from the Desklet app and got the error in the title. 
Looks like a really wonderful little Desklet! I hope there's enough details and it can get resolved.

**Comment by bdamer** [comment]
For what it's worth, seeing the same issue on my machine:
* Version 1.0.0
* Cinnamon 3.6.7
* Mint 18.3
* intel-microcode, version 3.20180807a.0ubuntu0.16.04.1

Identical error in glass.log:

    error t=2019-04-30T23:29:12.275Z Could not load desklet simple-system-monitor@ariel
    error t=2019-04-30T23:29:37.021Z No JS module 'simple-system-monitor@ariel' found in search path
    trace t=2019-04-30T23:29:37.022Z 
    <----------------
    Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:140:13
    Extension@/usr/share/cinnamon/js/ui/extension.js:115:5
    loadExtension@/usr/share/cinnamon/js/ui/extension.js:450:25
    _onEnabledDeskletsChanged@/usr/share/cinnamon/js/ui/deskletManager.js:203:16
    ---------------->

**Comment by NikoKrause** [comment]
Mint 18.3 is end of life next month.
The desklet loads on Mint 20.1 here.
Does this issue still happen for you?
