### ISSUE TITLE
googleCalendar@javahelps.com: desklet shows Days, Month and Weeks in English

### ISSUE THREAD

**Issue by kuehhe1** [linuxmint/cinnamon-spices-desklets#422]
Hello,
since the last google calendar update, all calendars are weekdays and months in long and short in english. How and where can I in which fileI adjust this in DE (German)?  In the older Version was it configured in the: ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js.
In the new Version i can't found it.

Best regards
kuehhe1

!-- Desklet's UUID should be in the title -->

```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json")

> {
    "uuid": "googleCalendar@javahelps.com",
    "description": "A desklet that displays your agenda based on Google Calendar",
    "name": "Google Calendar",
    "prevent-decorations": true,
    "cinnamon-version": [
        "3.4",
        "3.6",
        "3.8",
        "4.0"
    ],
    "last-edited": 1551075379
}

 * Cinnamon version - 4.0.10
 * Distribution - LinuxMin 19.1 Tessa
 * Graphics - Intel UHD Graphics 620 driver: i915 v: kernel 
 * Snippet of 

> ~/.cinnamon/glass.log info t=2019-04-12T12:02:48Z Cinnamon.AppSystem.get_default() started in 182 ms
info t=2019-04-12T12:02:48Z loading user theme: /home/kuehhe1/.themes/Mint-Button-Green/cinnamon/cinnamon.css
info t=2019-04-12T12:02:48Z added icon directory: /home/kuehhe1/.themes/Mint-Button-Green/cinnamon
info t=2019-04-12T12:02:48Z PlacesManager: Updating devices
info t=2019-04-12T12:02:48Z loaded at Fri Apr 12 2019 12:02:48 GMT+0200 (CEST)
info t=2019-04-12T12:02:48Z ExtensionSystem started in 2 ms
info t=2019-04-12T12:02:48Z SearchProviderManager started in 0 ms
info t=2019-04-12T12:02:49Z Loaded applet show-desktop@cinnamon.org in 38 ms
info t=2019-04-12T12:02:49Z Loaded applet calendar@cinnamon.org in 38 ms
info t=2019-04-12T12:02:49Z Role locked: tray
info t=2019-04-12T12:02:49Z Loaded applet systray@cinnamon.org in 12 ms
info t=2019-04-12T12:02:49Z Config file /home/kuehhe1/.local/share/cinnamon/desklets/TimeAndDate@nightflame/metadata.json
info t=2019-04-12T12:02:49Z Loaded desklet TimeAndDate@nightflame in 14 ms
info t=2019-04-12T12:02:49Z Loaded applet expo@cinnamon.org in 10 ms
info t=2019-04-12T12:02:49Z Loaded applet keyboard@cinnamon.org in 18 ms
info t=2019-04-12T12:02:49Z Loaded applet nvidia-prime@cinnamon.org in 62 ms
info t=2019-04-12T12:02:49Z Loaded applet ShutdownMenuWithIcons@LLOBERA in 40 ms
info t=2019-04-12T12:02:49Z Role locked: notifications
info t=2019-04-12T12:02:49Z Loaded applet notifications@cinnamon.org in 14 ms
info t=2019-04-12T12:02:49Z Loaded desklet googleCalendar@javahelps.com in 16 ms
info t=2019-04-12T12:02:49Z Role locked: panellauncher
info t=2019-04-12T12:02:49Z Loaded applet panel-launchers@cinnamon.org in 218 ms
info t=2019-04-12T12:02:49Z Loaded applet power@cinnamon.org in 20 ms
info t=2019-04-12T12:02:49Z Loaded applet window-list@cinnamon.org in 28 ms
info t=2019-04-12T12:02:49Z Loaded applet sound@cinnamon.org in 50 ms
info t=2019-04-12T12:02:49Z Loaded applet network@cinnamon.org in 50 ms
info t=2019-04-12T12:02:50Z Loaded applet menu@cinnamon.org in 650 ms
info t=2019-04-12T12:02:50Z AppletManager started in 1460 ms
info t=2019-04-12T12:02:50Z bbcwx (instance 40): refreshing forecast at 12:02:50
info t=2019-04-12T12:02:50Z Loaded desklet bbcwx@oak-wood.co.uk in 162 ms
info t=2019-04-12T12:02:50Z DeskletManager started in 1598 ms
info t=2019-04-12T12:02:50Z Cinnamon took 2120 ms to start
info t=2019-04-12T12:02:50Z Adding systray: redshift (24x24px)
info t=2019-04-12T12:02:50Z Resized redshift with normalized size (22x22px)
info t=2019-04-12T12:02:50Z Hiding systray: network
info t=2019-04-12T12:02:50Z Adding systray: hp-systray (24x24px)
info t=2019-04-12T12:02:50Z Resized hp-systray with normalized size (22x22px)
info t=2019-04-12T12:02:51Z Adding systray: thunderbird (24x24px)
info t=2019-04-12T12:02:51Z Resized thunderbird with normalized size (22x22px)
info t=2019-04-12T12:02:53Z Adding systray: mintupdate.py (24x24px)
info t=2019-04-12T12:02:53Z Resized mintupdate.py with normalized size (22x22px)
info t=2019-04-12T12:17:47Z bbcwx (instance 40): refreshing forecast at 12:17:47

 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by kuehhe1** [comment]
Habs selbst herausgefunden.
Die Sprachdateien z.B. >fr.po, it.po, de.po< sind nur für das _GUI Google-Calendar_ selbst vorgesehen und dort gespeichert:`~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/po`

Die Strings der _Kalendertage_ und _Monat_e sind in langer und kurzer Form in Englisch vorgegeben und lassen sich in der Datei "_xdate.js_" austauschen:`~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js`

Das Datumsformat (DD dd. MM > dddd dd.MM.yyyy) ist im _GUI Google-Calendar_ konfigurierbar und wird in der Datei _googleCalendar@javahelps.com.json_ gespeichert:`~/.cinnamon/configs/googleCalendar@javahelps.com/googleCalendar@javahelps.com.json`
Thema gelöst, Thanks

**Comment by kuehhe1** [comment]
Hello, the working google-calendar Desklet is already history after the update of "2019-04-14, 23:01 UTC".  > :( Symptom: Suddenly the Desklet did not work properly and did not show any appointments, a check in "Add Desklet" showed that there was an update, after that it does not work anymore, it does not open and instead just shows up as a little black one  Point on the desktop and also affects the font of the Dekette "Time and Date." Importing the saved old configuration only causes the calendar names to be entered in the Config GUI, followed by a brief screen flicker and nothing else  in the older version the package "gcalcli" was required, if that is still needed for or with the new version I can not refer to: https://cinnamon-spices.linuxmint.com/desklets/view/35 An uninstall of  "gcalcli" does not change anything.

**Comment by kuehhe1** [comment]
Hello, the working google-calendar Desklet is already history after the update of "2019-04-14, 23:01 UTC". > :( Symptom: Suddenly the Desklet did not work properly and did not show any appointments, a check in "Add Desklet" showed that there was an update, after that it does not work anymore, it does not open and instead just shows up as a little black one Point on the desktop and also affects the font of the Dekette "Time and Date." Importing the saved old configuration only causes the calendar names to be entered in the Config GUI, followed by a brief screen flicker and nothing else in the older version the package "gcalcli" was required, if that is still needed for or with the new version I can not refer to: https://cinnamon-spices.linuxmint.com/desklets/view/35 An uninstall of "gcalcli" does not change anything.

**Comment by NikoKrause** [comment]
ping author @slgobinath

@kuehhe1 is this issue still valid?

**Comment by kuehhe1** [comment]
Hello,
Yes the problem is solved with the current version

Best Regards kuehhe1
