### ISSUE TITLE
ViennaTextBasedWeather@f-istvan: How to pass quality gate

### ISSUE THREAD

**Issue by f-istvan** [linuxmint/cinnamon-spices-desklets#424]
Could you please help me to fix these quality issues:

1) `on_desklet_removed`: if I'm right this function is provided by the api.
2) `imports` is also provided by the framework.

Here is the report:
https://app.codacy.com/app/cinnamon-spices/cinnamon-spices-desklets/pullRequest?bid=6255201&prid=3434533#newIssuesView

Is there a way to run these checks on local machine before push? Are the rules available somewhere?

Thank you!

**Comment by NikoKrause** [comment]
Codacy seems to be removed from this repo
