### ISSUE TITLE
notes@schorschii: Warning when adding desklet: "This desklet contains function calls that could potentially cause Cinnamon to crash or freeze"

### ISSUE THREAD

**Issue by jeremy21212121** [linuxmint/cinnamon-spices-desklets#428]
After installing notes@schorschii, there is a warning in the Desklets UI: "This desklet contains function calls that could potentially cause Cinnamon to crash or freeze".

I found the function calls that trigger that warning [here](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py#L33). The specific function call triggering this warning in notes is `Cinnamon.get_file_contents_utf8_sync()`.

I changed two instances of that function call to `String(GLib.file_get_contents("/path/to/yourFile")[1])`, and that removed the error.

But then it dawned on me, perhaps that warning is there because a synchronous file read, in general, has the potential to crash Cinnamon (ie. if the file is really large). If that were the case, then using `GLib.file_get_contents()` instead of `Cinnamon.get_file_contents_utf8_sync()` would just be working around the warning but not actually fixing the underlying reason for the warning. Reading the commit message [here](https://github.com/linuxmint/cinnamon/commit/382338254f59b5e98cfc168accf45429808e69ae#diff-c4641b580bb45b188c5ae94c7f7a33cf) confirmed my suspicion that synchronous file reads are the issue.

Reading the [source code](https://stackoverflow.com/questions/15972338/gjs-read-file-synchronously) for `Cinnamon.get_file_contents_utf8_sync()`, it appears to just be using Glib's file_get_contents under the hood, combined with a few sanity checks.

So, if I wanted to actually fix the underlying reason for that warning, do I need to use an asynchronous file read function? I think that would not be practical, as the whole desklet seems to be inherently synchronous. Or would it suffice to just check the size of the text file before attempting to load it?

Thanks in advance. I'm a JS dev, but this is my first time diving into desklet/applet dev.

**Comment by Odyseus** [comment]
Hello, @jeremy21212121.

That message that you see is a warning, not an error. It's mostly there so, in the case of a Cinnamon crash/freeze/lock, you start looking the xlets that have that warning as possible culprits.

Using a synchronous file read function isn't inherently *bad* and not always is possible to replace with an asynchronous call. In fact, `Cinnamon.get_file_contents_utf8_sync()` [is used by Cinnamon itself in several places](https://github.com/linuxmint/cinnamon/search?q=Cinnamon.get_file_contents_utf8_sync&unscoped_q=Cinnamon.get_file_contents_utf8_sync).

Replacing the call to `Cinnamon.get_file_contents_utf8_sync()` with a call to `GLib.file_get_contents()` as you did might have removed the warning, but the possible problem that that message was warning you about is still there (a call to a synchronous file read function).

If you actually want to *"fix"* the issue, you could just use an asynchronous file read function. I have been using [`Gio.File.load_contents_async()`](https://lazka.github.io/pgi-docs/#Gio-2.0/classes/File.html#Gio.File.load_contents_async) in all my xlets for years now. Basic example usage:

```javascript
let file = Gio.file_new_for_path("/path/to/file");
file.load_contents_async(null, (aFile, aResponce) => {
    let success,
        contents,
        tag;

    try {
        [success, contents, tag] = aFile.load_contents_finish(aResponce);
    } catch (aErr) {
        global.logError(aErr.message);
        return;
    }

    if (!success) {
        global.logError("Error reading file.");
        return;
    }

    global.log(contents);
});
```

**Comment by NikoKrause** [comment]
ping author @schorschii
