### ISSUE TITLE
googleCalendar@javahelps.com desklet suddenly stopped working

### ISSUE THREAD

**Issue by FMaside** [linuxmint/cinnamon-spices-desklets#430]
Hi, I've been using the calendar desklet for the past months without any problems but, since a couple of days ago, it suddenly stopped showing up. When I try to activate it from the desklets app, it says that something went wrong when loading it. 

I used the command: python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py --list-calendars

And it shows the name of my calendars... and the I used the command: python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py 

And it shows this:  [{"calendar_color": "#9a9cff", "summary": "Carta descriptiva y primer parcial", "start_date": "2019-05-30", "start_time": "00:00", "end_date": "2019-05-31", "end_time": "00:00", "location": ""}]

Which are the active events I have in the calendar, so it seems everything is okay, but still... the desklet doesn't show... I don't have problems with any other desklet I use, by the way...

Is there a way to fix this? I really liked this one... :c

Greetings.

**Comment by claudiux** [comment]
Try this:
`python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py  --list-calendars | tr "\n" "," | sed s/,$/\\n/g`

Then, in the Settings of this desklet, set the `Calendar name(s)` entry to the value returned by the command above.

**Comment by NikoKrause** [comment]
ping author @slgobinath

Since there's no answer from @FMaside to @claudiux answer, I'm gonna close this issue.
