### ISSUE TITLE
googleCalendar@javahelps.com: [Feature request] Show every day an event that takes place over several days.

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-desklets#434]
```
 * Desklet version/Build date: 1559550584
 * Cinnamon version: 4.0.10
 * Distribution: Mint 19.1

 ```

Hi @slgobinath,

This is a feature request.

When an event takes place over several days, it is displayed only on the first day. Can you add an option to display it every day, please?

Many thanks for your great desklet!

Best regards.
claudiux

**Comment by slgobinath** [comment]
It looks like a bug. When I developed this desklet for the first time, I implemented the support for multiday events (I remember I tested with two day events). I will have a look at it.

**Comment by claudiux** [comment]
Thank you @slgobinath !

**Comment by slgobinath** [comment]
Confirmed the bug. I will push the fix in a few days.
