### ISSUE TITLE
googleCalendar@javahelps.com: Desklet working but only appears as a dot on my desktop.

### ISSUE THREAD

**Issue by hoppyjohn** [linuxmint/cinnamon-spices-desklets#448]
Google Calendar Desklet
UUID: googleCalendar@javahelps.com
Build 08-15-2019
Cinnamon version 4.0.10
Distribution - Mageia 7
Graphics - NVIDIA GK107 (GeForce GT 740) - driver NVIDIA 430.50
 
I've installed the desklet and made sure I installed all the dependencies.  But the calendar is not appearing on my desktop.  All I can see is a dot (if I click it, I get the Open Google Calendar, about, configure and remove this desklet options).   I ran  "python3 
 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py --list-calendars" and it returned my active Google calendars.  I've also tried rebooting my computer, and removing and reinstalling the desklet.

I've attached a screenshot of my desktop and circled the dot which is all I can see of the calendar desklet.
![Desktop screenshot](https://user-images.githubusercontent.com/56411588/66601761-a34e5980-eb76-11e9-9fc3-4d6d37209275.png)

**Comment by slgobinath** [comment]
Could you please try the updated version using gcalendar and let me know if the problem has been resolved or not.
