### ISSUE TITLE
One day late on desktop

### ISSUE THREAD

**Issue by andvenancio** [linuxmint/cinnamon-spices-desklets#459]
```
 * Desklet version/Build date: 2019-10-25 18:35 UTC
 * Cinnamon version: 4.0.10
 * Distribution: Mint 19.1
 * Python 3.6.8
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 5500

 ```

When I run the line command **python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py** I see the informations and they are ok, but on desktop they are showed with delay of 1 day. Example: today is "November 8", on desktop is showed "TODAY, NOVEMBER 7". All appointments are displayed one day late.

![image](https://user-images.githubusercontent.com/25935569/68484776-b22f3700-021c-11ea-8441-aea29a693e62.png)

On command **python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py** the day of appointment is November 8:

![image](https://user-images.githubusercontent.com/25935569/68485207-9bd5ab00-021d-11ea-9ede-ce68a8793d1f.png)

**Comment by slgobinath** [comment]
Hi,

Thanks for reporting this issue. It will be fixed with the PR https://github.com/linuxmint/cinnamon-spices-desklets/pull/460

**Comment by andvenancio** [comment]
Hi,
I updated Google Calendar Desklet but it still has problem.
Today is the November 11, the calendar shows my schedule of tomorrow (November 12) but indicating as if it were on the day 11:
![image](https://user-images.githubusercontent.com/25935569/68619063-7230b400-04a9-11ea-85ae-98b94ee9e8e9.png)

**Comment by slgobinath** [comment]
Could you please open the file `~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js` and check line number 99 to 105. It should look like this:

```javascript
...
    function T(e, n, r) {
        for (var i, o = u.parsers, s = 0; s < o.length; s++) {
            i = o[s](e, n, r);
            if (i) return i;
        }
        return r[0] = new t(e), r
    }
...
```

**Comment by andvenancio** [comment]
On my system this function it's different:

`    
function T(e, n, r) {
   for (var i, o = u.parsers, s = 0; s < o.length; s++)
      if (i == o[s](e, n, r)) return i;
         return r[0] = new t(e), r
}
`

How can I update this to work correctly?

**Comment by slgobinath** [comment]
Hi,
Just replace the function T by the above one and save it. Then restart Cinnamon (right click on task bar, Troubleshoot -> Restart Cinnamon)

**Comment by andvenancio** [comment]
Thank you @slgobinath.
Now it's working well done.
