### ISSUE TITLE
 UUID: googleCalendar@javahelps.com - Not displaying in Cinnamon 4.4

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-desklets#477]
@javahelps.com
![Screenshot from 2019-12-02 18-22-54](https://user-images.githubusercontent.com/38849451/69955764-01713a80-1531-11ea-83eb-d5a7e4b1551c.png)
 * Desklet version/Build date - Updated on 2019-11-24 17:38:24
 * Cinnamon version 4.4
 * Distribution - Arch
 * Graphics hardware AMD/ATI Radeon
 * Snippet or attachment of ~/.cinnamon/glass.log
info t=2019-12-02T17:54:00Z Loaded desklet googleCalendar@javahelps.com in 18 m
After restart:
info t=2019-12-02T18:16:10Z Loaded desklet googleCalendar@javahelps.com in 0 ms
info t=2019-12-02T18:16:10Z Loaded desklet googleCalendar@javahelps.com in 0 ms
 * Snippet or attachment of ~/.xsession-errors
Cjs-Message: 17:54:00.284: JS LOG: [LookingGlass/info] Loaded desklet googleCalendar@javahelps.com in 18 ms
after restart:
Cjs-Message: 18:16:10.927: JS LOG: [LookingGlass/info] Loaded desklet googleCalendar@javahelps.com in 0 ms
Cjs-Message: 18:16:10.927: JS LOG: [LookingGlass/info] Loaded desklet googleCalendar@javahelps.com in 0 ms
 ```
<!-- Author list: https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/.github/CODEOWNERS -->

**Notify author of desklet**
googleCalendar@javahelps.com

**Issue**
Appears to load, but no display of icon or desklet.

**Expected behaviour**
Display Google calendar

**Other information**
**+** still showing bold, **-** grey.
To stop attempts to load, file deleted from/local/share/cinnamon/desklets/

**Comment by two-dogs** [comment]
from spotchat server channel #linuxmint-help, @Odyseus explains to crazytux how to fix issue

[22:13] <Odyseus> CrazyTux: The exact locations is: ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com. Edit the metadata.json file in there.
........
[22:14] <Odyseus> CrazyTux: Odyseus CrazyTux: You could "make compatible" that desklet with your current Cinnamon version. Just add the it to the cinnamon-version key inside its metadata.json file. Example: "cinnamon-version": ["3.4", "3.6", "3.8", "4.0", "4.2", "4.4"]

**Comment by Padre2** [comment]
@two-dogs Thanks, that was the first thing I tried and it does stop the compatibility warning allowing it to load, but nothing appears to the desktop.  Am I missing something?

**Comment by mosge** [comment]
It appears only as a small ball and very little visible because the transparency is set to 50%. However, the desklet doesn't work at this time because "The Connect with Google option is temporarily disabled for this application. The app has not yet been verified by Google to use Google Connect"
You will see this warning when you try to sign in to your Google Account

**Comment by Padre2** [comment]
@mosge  Thanks, I read about the verification issue, but would have assumed that the applet had received a verification at some time in the past. Did it expire or were changes made?
There is nothing on my desktop, but something must be connecting because I received a notification of a Google Calendar reminder!

**Comment by Padre2** [comment]
Installation information is confusing, if applied to Arch. There are no `python3` packages.  Installed are `python version 3.8.0` and other packages:   `python-pip python-setuptools python-dateutil` python-oauth2client.  However, `python-googleapi` does not seem to exist. Found and installed `python-google-api-python-client 1.7.11`, perhaps not correct and still no desklet.

**Comment by Padre2** [comment]
@javahelps.com  Installed the update.  Now on Cinnamon version 4.7.  Still no desklet.

**Comment by Padre2** [comment]
Back in February I finally got  the applet to work after authenticating with Google,  Some days ago there was an update introducing a `gcalendar` package that stopped it working, but I fixed it after understanding how `gcalendar' works.  Today the applet was updated and stopped working again. After reinstalling I found that `gcalendar` has errors.  I will open a new issue.
