### ISSUE TITLE
 Disk Space@schorschii: can't list 16 gb dual stick ram properly , lists one stick 8 gb instead of whole

### ISSUE THREAD

**Issue by Leopard1907** [linuxmint/cinnamon-spices-desklets#479]
```
 * Desklet version/Build date : Version 1.4 (2019-11-16 18:47:38)
 * Cinnamon version : 4.4.5
 * Distribution : Mint 19.3
 * Nvidia GTX 1050 440.40 ( not related to the issue but template asks for it)
 * Snippet or attachment of ~/.cinnamon/glass.log : There is no such log exists
 * Snippet or attachment of ~/.xsession-errors : There is no such directory and log exists

 ```

**Notify author of desklet**
@schorschii

**Issue**

Just like it says in the title. On a 16 gb system ( 8x2 dual stick ) , ram usage desklet only shows 8 gb as total and as adjust percentage of ram usage according to that. Which is wrong.

**Steps to reproduce**

Installing this desklet and using ram usage info function

**Expected behaviour**

Properly recognizing total ram value. I have a strong suspicion that this applet doesn't actually read the total ram value but instead of it, just relying swap area size and the behaviour of end user about sticking to setup defaults. Since it advises you to have a swap area as big as your total ram which i always find it as nonsense. 

I have 8 gb swap area btw. Recently i got a second stick.

You can see my setup details on the gist below.

**Other information**

inxi -Fxz output:

https://gist.github.com/Leopard1907/8de777ba8f6db20c338699de7cd66f29

**Comment by Leopard1907** [comment]
Update: That is weird and i didn't caught it earlier.

Desklet actually shows the correct ram size at the beginning , aka when you boot your pc. But after that , over time it slowly shrinks and after like 45 minutes it dips down to 8 gb level.

**Comment by schorschii** [comment]
Thanks for your detailed report. I'm working on a fix.

**Comment by Leopard1907** [comment]
Issue is not fixed by 1.5

Just putting up a screenshot with this. As you can see, after 20 mins usage.

![Ekran Görüntüsü - 2019-12-23 19-17-20](https://user-images.githubusercontent.com/24878978/71368419-f605b200-25b8-11ea-96b6-83c60d79ba39.png)

**Comment by Leopard1907** [comment]
@brownsr It is not fixed.

**Comment by schorschii** [comment]
@Leopard1907 Can you please restart cinnamon to ensure cinnamon really loaded the new version? (When updating manually by unpacking the files in `~/.local/share/cinnamon/desklets` cinnamon must be restarted in order to load the new version.)
If it persists please paste the output of the `free` command here at the time the desklet shows wrong values. Thanks.

**Comment by Leopard1907** [comment]
I've updated it via cinnamon desklets app so no manual update.

I will purge desklet anyway. And try with a fresh desklte installation.

**Comment by Leopard1907** [comment]
After purging the desklet and installing it fresh problem seems to be gone. Thanks for your interest.
