### ISSUE TITLE
googleCalendar@javahelps.com Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by mrprajesh** [linuxmint/cinnamon-spices-desklets#492]
```
 * Build date ( in "metadata.json" 1578305223  and last modified 2020-01-06 10:07 UTC)
 * Cinnamon version 3.8
 * Distribution - (Mint 19)
 ```
@slgobinath 

**Issue**
It seems like Google has temporarily disabled sign in. Below is error when trying to signing using the auth link.

**Error**
Sign in with Google temporarily disabled for this app
This app has not yet been verified by Google in order to use Google Sign in.

To reproduce: 
May be to remove existing access to the app from google account>security>third-party and try to approve access by sign in again. Reading other issues looks like it did not affect existing uses but new users of the app.

**Comment by bridnour** [comment]
I've found a workaround:

1. Follow the optional API instructions at https://github.com/insanum/gcalcli#login-information.

2. This will give you a Client ID and Client Secret.

3. Edit ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py and replace the default ID and Secret with the one's you created.

4. Run ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py.

5. Copy the link as instructed. You will get a warning screen that you'll have to work through (look for an "advanced" button on the screen). 

6. Copy the text you get into the prompt provided.

7. This should allow you to use the desklet. (At least it worked for me.)

**Comment by slgobinath** [comment]
Hi,
Sorry for not responding here. Google is verifying the desklet but it takes forever. I've written a medium post explaining how to add your own credentials here:

https://medium.com/@lgobinath/how-to-use-google-calendar-desklet-41d8aa0dbedd

Above link is added to the read me in the PR #496 

I hope Google will verify the desklet asap.

**Comment by mrprajesh** [comment]
Thank you @bridnour  and @slgobinath 
It works now.
