### ISSUE TITLE
clock@schorschii fails to start after Arch update

### ISSUE THREAD

**Issue by herbstschweigen** [linuxmint/cinnamon-spices-desklets#498]
* Version 1.5 (2019-11-24 11:15:12)
 * Cinnamon version 4.4.8
 * Arch Linux with Kernel 5.5.8-arch1-1
 * Intel Corporation 4th Gen Core Processor Integrated Graphics Controller, i915

LookingGlass log:
info t=2020-03-08T07:54:02Z Loaded applet panel-launchers@cinnamon.org in 168 ms
**error t=2020-03-08T07:54:02Z [[boxed instance proxy GIName:GLib.Error jsobj@0x7f09304760a0 native@0x556db763b880]]: Failed to evaluate 'main' function on desklet: clock@schorschii/6**
info t=2020-03-08T07:54:02Z Loaded applet power@cinnamon.org in 32 ms
info t=2020-03-08T07:54:02Z Role locked: notifications
info t=2020-03-08T07:54:02Z Loaded applet notifications@cinnamon.org in 20 ms
info t=2020-03-08T07:54:02Z Loaded desklet battery@schorschii in 70 ms

**error t=2020-03-08T07:54:02Z 
[clock@schorschii]: Desklet clock@schorschii: Could not create desklet object.
[clock@schorschii]: Error importing desklet.js from clock@schorschii**
info t=2020-03-08T07:54:02Z DeskletManager started in 606 ms

.xsession-errors:
Cjs-Message: 07:54:02.164: JS LOG: [LookingGlass/error] [[boxed instance proxy GIName:GLib.Error jsobj@0x7f09304760a0 native@0x556db763b880]]: Failed to evaluate 'main' function on desklet: clock@schorschii/6
Cjs-Message: 07:54:02.165: JS LOG: [LookingGlass/trace] 
<----------------
logError@/usr/share/cinnamon/js/ui/extension.js:134:17
_createDesklets@/usr/share/cinnamon/js/ui/deskletManager.js:332:9
_loadDesklet@/usr/share/cinnamon/js/ui/deskletManager.js:298:23
finishExtensionLoad@/usr/share/cinnamon/js/ui/deskletManager.js:177:14
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:277:17
---------------->
Cjs-Message: 07:54:02.181: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 32 ms
Cjs-Message: 07:54:02.193: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 07:54:02.201: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 20 ms
Cjs-Message: 07:54:02.271: JS LOG: [LookingGlass/info] Loaded desklet battery@schorschii in 70 ms
Cjs-Message: 07:54:02.271: JS LOG: [LookingGlass/error] 
[clock@schorschii]: Desklet clock@schorschii: Could not create desklet object.
[clock@schorschii]: Error importing desklet.js from clock@schorschii
Cjs-Message: 07:54:02.271: JS LOG: [LookingGlass/trace] 
<----------------
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:278:23
---------------->
Cjs-Message: 07:54:02.272: JS LOG: [LookingGlass/info] DeskletManager started in 606 ms
Cjs-Message: 07:54:02.295: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 24 ms

**Notify author of desklet**
@schorschii 

After running pacman -Syu and rebooting this morning, the clock@schorschii did not start and Cinnamon reported the errors above.

**Comment by schorschii** [comment]
I'm having trouble reproducing this issue. I installed a fresh Arch in a VM and the clock desklet works fine. Can you please check if the problem persists on a fresh installation?

**Comment by herbstschweigen** [comment]
Hi, thanks for your reply. I tried uninstalling and reinstalling the clock desklet, but that does not fix the error. I don't know when I can get to do a check with a new VM install, as Arch is my main system and due to the current situation I need my machine for home office work.
For now I have uninstalled the analog clock desklet. 
Bleib gesund!

**Comment by herbstschweigen** [comment]
Does not occur any more with Cinnamon 4.6.0, hence closing the issue.
