### ISSUE TITLE
Simple system monitor Not Loading on Cinnamon 4.4.8

### ISSUE THREAD

**Issue by chromer030** [linuxmint/cinnamon-spices-desklets#501]
Simple system monitor Desklet

 * Cinnamon 4.4.8
 * Arch linux
 *  Intel HD 630

This Desklet is great but not loading on cinnamon 4.4.8.

**Comment by lezandto** [comment]
cinnamon 4.4.8?

**Comment by chromer030** [comment]
even on latest version it's mpt working.
