### ISSUE TITLE
Strange link in footer of https://cinnamon-spices.linuxmint.com/

### ISSUE THREAD

**Issue by OndrejMalek** [linuxmint/cinnamon-spices-desklets#504]
**Issue**
Link http://developer.linuxmint.com/reference/git/cinnamon-tutorials/extension-system.html takes me to some library. Is it intentional? Does not seems so. Where are development docs?

**Comment by NikoKrause** [comment]
Hey, where do I find this link on the website?

**Comment by OndrejMalek** [comment]
Not 100% sure now, but probably 'Development' in the footer
![image](https://user-images.githubusercontent.com/6736907/98952944-57e64780-24fc-11eb-89d2-39e3ed717733.png)

Now it seems to work properly. It  took me to some page out of domain asking me to pay for library subscription. It looked like fraud to me.
