### ISSUE TITLE
googleCalendar@javahelps.com

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-desklets#540]
@javahelps.com

```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json") 
Cannot open About and not in the metadata.json file. Latest update.
 * Cinnamon version:  4.6
 * Distribution:  Arch
 * Graphics hardware: ATI/Radeon

[gcalendar_errors.txt](https://github.com/linuxmint/cinnamon-spices-desklets/files/4814268/gcalendar_errors.txt)

 * Snippet or attachment of ~/.cinnamon/glass.log
Cjs-Message: 22:46:42.784: JS LOG: [LookingGlass/info] Installing settings for googleCalendar@javahelps.com
Cjs-Message: 22:46:42.787: JS LOG: [LookingGlass/info] Settings successfully installed for googleCalendar@javahelps.com

 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@javahelps.com

**Issue**
Stopped working.

**Steps to reproduce**
Update to latest version.
Reinstall desklet.
Run `gcalendar`.
Errors shown in terminal.
Not working, no desklet.

**Expected behaviour**
Authentication with gcalendar
Desklet on on desktop,

**Other information**
I had finally got the old version working by authenticating with Google and has worked perfectly for several months.

After an update a few days ago the desklet disappeared and I went to the desklet web page and read about  `gcalendar`, installled it.
After several tries was able tauthenticte the desklet and get it up and working as before.
Today, a new update seems to have broken `gcalendar` (see attached error file).

**Comment by slgobinath** [comment]
Hi,
Can you try this:

```
sudo pip3 uninstall rsa
sudo pip3 install rsa==4.0
```

Then run `gcalendar`

**Comment by Padre2** [comment]
Hello,
Thanks for your quick response.  I had seen the `rsa` version issue in the error file, but unsure how to change it and was getting late in the day.

I ran the above code and it resolved the issue. Great to have it working again.
The result was as follows:
``zsh 921 % sudo pip3 install rsa==4.0
Collecting rsa==4.0
  Downloading rsa-4.0-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3.8/site-packages (from rsa==4.0) (0.4.8)
Could not build wheels for pyasn1, since package 'wheel' is not installed.
Installing collected packages: rsa
Successfully installed rsa-4.0`

I am a single user, so presume that the missing `wheel` package is not an issue.

**Comment by slgobinath** [comment]
I don' think so. Glad it fixed the issue. The Google Calendar API strictly needs rsa version between `rsa<4.1,>=3.1.4`. Hope you enjoy the desklet.

Please close this issue if the issue has been solved.

Thanks

**Comment by Padre2** [comment]
Hi Gobinath,
It is a very useful desklet popping up events and reminders on my desktop. Google authentication can be a pain. Thanks again for your work on it.

**Comment by Padre2** [comment]
Hi Gobinath,
It is a very useful desklet popping up events and reminders on my desktop. Google authentication can be a pain. Thanks again for your work on it.
