### ISSUE TITLE
hostcheck@schorschii: how do i setup up the Host check

### ISSUE THREAD

**Issue by dave841** [linuxmint/cinnamon-spices-desklets#541]
```
 * Host check version 1.0 2019-12-26 11.11.14
    cinnamon --version 4.4.8
 * Distribution - (Mint 19.3 Cinnamon
 * Graphics hardware RADEON RX 580
 * Snippet or attachment of ~/.cinnamon/glass.log
![Screenshot from 2020-06-22 18-04-26](https://user-images.githubusercontent.com/60449271/85315384-e0fbd400-b4b2-11ea-8fad-ef30b103bcd2.png)

 * Snippet or attachment of ~/.xsession-errors

 ```

<!-- Author list: Host Check app
**Notify author of schorschii)
@

**Issue**
 i have a problem how do i setup the app. all i get is /bin/ping and /usr/bin/curl which is not installed
![Screenshot from 2020-06-22 18-04-26](https://user-images.githubusercontent.com/60449271/85315667-61bad000-b4b3-11ea-8ff7-70147749bfda.png)

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by NikoKrause** [comment]
ping author @schorschii

**Comment by schorschii** [comment]
Hi @dave841 
What exactly is the problem? Does it show "CRIT" but your website is available? Please ensure curl is installed as mentioned in the readme: https://cinnamon-spices.linuxmint.com/desklets/view/49
