### ISSUE TITLE
Repo: Gulp utility script no longer available

### ISSUE THREAD

**Issue by fabscav** [linuxmint/cinnamon-spices-desklets#543]
The `readme.md` describes the possibility of "auto-reloading desklets" using a gulp utility script, yet it seems this script has been deleted from the repository a while ago (aa133a2e148cf473f26e06bcbf4fb3c1da6a92b6).

Was it not meant to be deleted or is the `readme.md` outdated?

**Comment by NikoKrause** [comment]
The README.md was outdated. I've removed that reference in the README.md: https://github.com/linuxmint/cinnamon-spices-desklets/pull/622/files
