### ISSUE TITLE
[system-monitor-graph@rcassani] Text-Size for nvme-drives

### ISSUE THREAD

**Issue by schinfo** [linuxmint/cinnamon-spices-desklets#544]
![Bildschirmfoto vom 2020-07-06 12-59-07](https://user-images.githubusercontent.com/26834276/86586980-1d3a3480-bf89-11ea-884f-96c7f7bcd7a3.png)

 ```

@rcassani

**Issue**
Text-sice is to big for nvme-drives

**Comment by rcassani** [comment]
The feature to change the text to display for variable and the size of its text will be added in a future version

**Comment by rcassani** [comment]
@schinfo, The issue with the label positioning has been fixed in #575.
The Desklet also allows the use of custom labels for HDD.

**Comment by rcassani** [comment]
@schinfo, can we close this issue?
