### ISSUE TITLE
googleCalendar@javahelps.com Failed to connect Google Calendar

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-desklets#545]
```
 * Desklet version/Build date Updated on 2020-06-20 18:25:47
 * Cinnamon version:  4.6.6
 * Distribution:  Arch
 * Graphics hardware ATI/Radeon
 * Snippet or attachment of ~/.cinnamon/glass.log
info t=2020-07-11T16:13:30Z Loaded desklet googleCalendar@javahelps.com in 276 ms
 * Snippet or attachment of ~/.xsession-errors

 ```
`Unknown Error`
`[boxed instance proxy GIName:GLib.Error jsob@0x7f4f201da580 native@0x55869f1994a0]`

**Notify author of desklet**
@javahelps.com

**Issue**
After changing calendars and after resetting the applet and running `gcalendar` in terminal ->
`Failed to connect Google Calendar`

**Steps to reproduce**
Run `gcalendar` in the terminal

**Expected behaviour**
Running `gcalendar` connects to Google Calendar

**Other information**
After sorting the recent `gcalendar` authentication method, the calendars appeared as expected.
I had unchecked a Formula 1 Calendar, because of cancellation of the races.
After the start of the races last week I checked the Formula 1 Calendar again, but there were errors in the calendar and I selected a calendar from another source, but this caused duplication and I deleted all F1 calendars in the main Google Calendar and installed a new one (there are several sources).
The Formula 1 Calendar now used and other unrelated calendars display correctly in Google Calendar on an Android mobile and on a desktop.
I have removed and reinstalled the desklet and tried resetting, reloading many times. 
I am sometimes getting the error message above in place of the calendar details.

**Comment by slgobinath** [comment]
Looks like something similar to this issue: https://github.com/slgobinath/gcalendar/issues/2
@Padre2 please check if this the same problem. If so, please share your terminal output after running `gcalendar` in https://github.com/slgobinath/gcalendar/issues/2

**Comment by Padre2** [comment]
@slgobinath 
zsh 1002 % gcalendar                         
Failed to connect Google Calendar

**Comment by slgobinath** [comment]
I have made some changes to `gcalcli` to debug this issue. Would you mind running these commands to get the debug error message and share with me:

```
git clone https://github.com/slgobinath/gcalendar.git
cd gcalendar
python3 -m gcalendar --debug
```

**Comment by Padre2** [comment]
@slgobinath 
```<victor@phenom:~>
zsh 1003 % git clone https://github.com/slgobinath/gcalendar.git
Cloning into 'gcalendar'...
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 78 (delta 37), reused 59 (delta 22), pack-reused 0
Unpacking objects: 100% (78/78), 30.01 KiB | 130.00 KiB/s, done.
[Sun 20/07/12 19:27 WIB][pts/0][x86_64/linux-gnu/5.7.7-zen1-1-zen][5.8]
<victor@phenom:~>
zsh 1004 % cd gcalendar
[Sun 20/07/12 19:28 WIB][pts/0][x86_64/linux-gnu/5.7.7-zen1-1-zen][5.8]
<victor@phenom:~/gcalendar>
zsh 1005 %F{magenta}(%fgit%F{magenta})%F{yellow}-%F{magenta}[%F{green}master%F{magenta}]%f % python3 -m gcalendar --debug
Failed to connect Google Calendar
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/victor/gcalendar/gcalendar/__main__.py", line 203, in <module>
    main()
  File "/home/victor/gcalendar/gcalendar/__main__.py", line 197, in main
    raise ex
  File "/home/victor/gcalendar/gcalendar/__main__.py", line 185, in main
    calendar_events = g_calendar.list_events(selected_calendars, start_time, end_time, time_zone)
  File "/home/victor/gcalendar/gcalendar/gcalendar.py", line 89, in list_events
    events = self.retrieve_events(calendar_list_entry["id"], calendar_list_entry["backgroundColor"],
  File "/home/victor/gcalendar/gcalendar/gcalendar.py", line 112, in retrieve_events
    start_date_time = datetime.strptime(
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %```

**Comment by Padre2** [comment]
@slgobinath 
Namaste,  It seems like there is an issue with the F1 Calendar date/time which is set at  GMT+00:00. My local time is GMT+7.00.  This is not a problem with the desktop. or Android mobile , which are set to my local time.

**Comment by slgobinath** [comment]
Thanks. Looks like the returned time does not align with the expected format. Could you please modify the `gcalendar.py` as shown below and share the printed date time values to check the format.

Add `print(event["end"]["dateTime"])` just after line number 111. After the change the code should look like this:

```python
...
                # Extract the start and end time
                if "dateTime" in event["start"]:
                    print(event["end"]["dateTime"])
                    start_date_time = datetime.strptime(
                        "".join(event["start"]["dateTime"].rsplit(":", 1)), "%Y-%m-%dT%H:%M:%S%z")
                    end_date_time = datetime.strptime(
                        "".join(event["end"]["dateTime"].rsplit(":", 1)), "%Y-%m-%dT%H:%M:%S%z")
                    calendar_event["start_date"] = str(start_date_time.date())
                    calendar_event["start_time"] = str(start_date_time.time()).rsplit(":", 1)[0]
                    calendar_event["end_date"] = str(end_date_time.date())
                    calendar_event["end_time"] = str(end_date_time.time()).rsplit(":", 1)[0]
...
```

**Comment by Padre2** [comment]
I added the line above and ran gcalendar. The output is as before; Failed to connect Google Calendar.
Did I misunderstand?

**Comment by slgobinath** [comment]
It will still fail but it should print the event time before the error message. Knowing the time format, I can fix the code.

**Comment by Padre2** [comment]
If running `gcalendar`, with the line to print added, does not produce any `dateTime` output, then what should be done?

The calendar I am using is from: https://formulaonecalendar.com/

I have reinstalled the URL for the  F1 calendar from the above website and have noticed some behaviour of the applet that may give you some clues as to what is happening:

If the F1 Calendar is not checked in the applet configuration then other calendars will appear. They disappear again after the F1 calendar is checked.

I noted a date-time llne now appearing prior to the line Failed to connect Google Calendar. 
`zsh 903 [255] % gcalendar`
`2020-07-17T10:30:00Z`
`Failed to connect Google Calendar`

The above time-date line shows the date advanced 4 days (13 -> 17) and the time is fixed (does not change) at 12:30:00Z !?

**Comment by Padre2** [comment]
I moved the print line to below line 119
 with the following output:
```[Mon 20/07/13 20:08 WIB][pts/0][x86_64/linux-gnu/5.7.7-zen1-1-zen][5.8]
<victor@phenom:~>
zsh 903 [255] % gcalendar
2020-07-13T21:00:00+07:00
Failed to connect Google Calendar

**Comment by slgobinath** [comment]
I am able to reproduce the problem. I will fix this soon and let you know here.
Thank you for your support to find the problem.

**Comment by slgobinath** [comment]
@Padre2 I have fixed the issue in GitHub. Could you please test it by executing the following command and let me know if it works?

Please clone a new copy (you can delete the old gcalendar folder)
```
git clone https://github.com/slgobinath/gcalendar.git
cd gcalendar
python3 -m gcalendar
```

If `python3 -m gcalendar` prints your events from all your calendars (including the F1 calendar), I will release a new version including the fix.

**Comment by Padre2** [comment]
@slgobinath 
Success, the command prints the calendars including the F1 Calendar, however the F1 times in the terminal are GMT/UTC. Will they be shown as local times in the desklet?

**Comment by slgobinath** [comment]
I will take care of the conversion.
Will release a new version including the fix soon.

Thank you very much for your suport.

**Comment by Padre2** [comment]
@slgobinath 
Have updated the desklet. Running `gcalendar` still returns  `Failed to connect Google Calendar`
If F1 not checked, the other calendars are displayed. If F1 checked, a small square is now displayed, before nothing was displayed.
Reloading the desklet produced the following in Melange:
Failed to connect Google Calendar
```
info t=2020-07-15T09:36:26Z Reloading desklet: googleCalendar@javahelps.com/39
info t=2020-07-15T09:36:26Z Loaded desklet googleCalendar@javahelps.com in 130 ms
warning t=2020-07-15T09:36:26Z Invalid or null source id used when attempting to run Mainloop.source_remove()
overrideDumpStack/global.dump_gjs_stack@/usr/share/cinnamon/js/ui/overrides.js:103:42
overrideMainloop/Mainloop.source_remove@/usr/share/cinnamon/js/ui/overrides.js:137:13
on_desklet_removed@/home/victor/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:171:9
destroy/<.onComplete<@/usr/share/cinnamon/js/ui/desklet.js:133:32
_addHandler/params[name]@/usr/share/cinnamon/js/ui/tweener.js:256:13
_callOnFunction@resource:///org/cinnamon/cjs/modules/tweener/tweener.js:204:13
_updateTweenByIndex@resource:///org/cinnamon/cjs/modules/tweener/tweener.js:338:9
_updateTweens@resource:///org/cinnamon/cjs/modules/tweener/tweener.js:351:18
_onEnterFrame@resource:///org/cinnamon/cjs/modules/tweener/tweener.js:366:10
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
ClutterFrameTicker.prototype._onNewFrame@/usr/share/cinnamon/js/ui/tweener.js:413:9
ClutterFrameTicker.prototype._init/<@/usr/share/cinnamon/js/ui/tweener.js:389:17
```

**Comment by slgobinath** [comment]
Sorry still I haven't released the new version. Could you please test it one more time before the release.

```
git clone https://github.com/slgobinath/gcalendar.git
cd gcalendar
python3 -m gcalendar
```

You don't need to update the desklet. After releasing the new version of `gcalendar`, I will let you know. Once you update it the problem should be fixed.

Thanks

**Comment by Padre2** [comment]
I reinstalled the desklet because I had a notification og a new version.
zsh 910 [129] %F{magenta}(%fgit%F{magenta})%F{yellow}-%F{magenta}[%F{green}master%F{magenta}]%f % python3 -m gcalendar

2020-07-15:00:00 - 2020-07-16:00:00	Sunrise: 06:06, Sunset: 17:53	
2020-07-16:00:00 - 2020-07-17:00:00	Sunrise: 06:06, Sunset: 17:53	
2020-07-17:00:00 - 2020-07-18:00:00	Sunrise: 06:06, Sunset: 17:53	
2020-07-17:16:00 - 2020-07-17:17:30	Practice 1 (Hungarian Grand Prix)	Mogyoród
2020-07-17:20:00 - 2020-07-17:21:30	Practice 2 (Hungarian Grand Prix)	Mogyoród
2020-07-18:00:00 - 2020-07-19:00:00	Sunrise: 06:06, Sunset: 17:53	
2020-07-18:17:00 - 2020-07-18:18:00	Practice 3 (Hungarian Grand Prix)	Mogyoród
2020-07-18:20:00 - 2020-07-18:21:00	Qualifying (Hungarian Grand Prix)	Mogyoród
2020-07-19:00:00 - 2020-07-20:00:00	Sunrise: 06:06, Sunset: 17:53	
2020-07-19:20:10 - 2020-07-19:22:10	2020 Hungarian Grand Prix	Mogyoród
2020-07-20:00:00 - 2020-07-21:00:00	Sunrise: 06:06, Sunset: 17:54	
2020-07-21:00:00 - 2020-07-22:00:00	Sunrise: 06:05, Sunset: 17:54	
2020-07-22:00:00 - 2020-07-23:00:00	Sunrise: 06:05, Sunset: 17:54

**Comment by slgobinath** [comment]
So the gcalendar is working fine right?

**Comment by Padre2** [comment]
Yes, as above from the cloned copy.

**Comment by Padre2** [comment]
I presume you will now update gcalendar in the repository.

**Comment by slgobinath** [comment]
Yup. Not right now. Within 8 - 10 hours :-)

**Comment by Padre2** [comment]
No rush. :-)

**Comment by Padre2** [comment]
No rush. For interst i copied the cloned gcalendar directort to the site packages directory and every is working fine. :-) :+1:

**Comment by slgobinath** [comment]
@Padre2 I have released the new version `0.3` yesterday (Not released for Arch yet). Please close this issue if it has been fixed.

Once again thank you for your help in finding the issue.

**Comment by Padre2** [comment]
You are welcome. I admire your work with Python and it’s been a privilege to contribute to solving the issues.
I was inspired and yesterday installed IDLE, so that I can start learning more Python. :-)

**Comment by slgobinath** [comment]
Great it's good to hear that
All the best for your programming endeavour!!
