### ISSUE TITLE
[diskspace@schorschii] Applet sometimes receive erroneous clicks and get stuck in move mode

### ISSUE THREAD

**Issue by solorvox** [linuxmint/cinnamon-spices-desklets#553]
Cinnamon: 4.6.6
Mint 20
Nvidia RTX2070 / 440.100

**Notify author of desklet**
@schorschii
Sometimes the desklet receives an erroneous click notification and gets stuck in move mode.  When this happens, they appear to be selected (filled with selection colour) and follow mouse around.  This makes it hard to fix since releasing the button doesn't seem to work.

A solution might be you added a toggle to "lock" them in config so they ignore left clicks and only respond to right clicks or via applet control panel.

I'm running only two desklets, RAM and Diskspace.

**Comment by schorschii** [comment]
I'm also experiencing this issue from time to time, but not only with my disk space desklet. It seems to be a general Cinnamon issue.

**Comment by ipimpat** [comment]
It happens with the CPU load desklet too, which I'm author of.

I also think that this is a bug in Cinnnamon.

I use the Clock desklet and CPU load desklet, and have also experienced with both.

I'm btw author of the CPU load desklet.

**Comment by NikoKrause** [comment]
This seems to be a desklet issue per se https://github.com/linuxmint/cinnamon/issues/9622
