### ISSUE TITLE
googleCalendar@javahelps.com: Unknown Error: [boxed instance proxy GIName: GLib.Error…

### ISSUE THREAD

**Issue by Mr-Jiggs** [linuxmint/cinnamon-spices-desklets#558]
Updated on 2020-07-28 11:02:57
Cinnamon 4.6.6
Mint 20
ATI FirePro W2100 / Oland GL
No 'glass.log'
~/.xsession-errors:
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cjs-Message: 10:48:12.329: JS LOG: [LookingGlass/info] Installing settings for googleCalendar@javahelps.com
Cjs-Message: 10:48:12.329: JS LOG: [LookingGlass/info] Settings successfully installed for googleCalendar@javahelps.com
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (workdir specified) (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (workdir specified) (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (workdir specified) (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (workdir specified) (fd close requested) 

(cinnamon:1479): St-WARNING **: 10:51:45.696: Did not find color property '-gradient-start'

(cinnamon:1479): St-WARNING **: 10:51:45.696: Did not find color property '-gradient-end'

(cinnamon:1479): St-WARNING **: 10:51:46.452: Did not find color property '-gradient-start'

(cinnamon:1479): St-WARNING **: 10:51:46.452: Did not find color property '-gradient-end'
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cjs-Message: 10:52:04.795: JS LOG: [LookingGlass/info] bbcwx (instance 1): refreshing forecast at 10:52:04
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested)

**Comment by DutchessNicole** [comment]
I'm seeing the same issue today:
`Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (workdir specified) (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (workdir specified) (fd close requested)`
One line appears each time I attempt to refresh the desklet.

Running `gcalendar --list-calendars` does give the correct output and lists the calendars that were authorized.

**Comment by DaniKoza** [comment]
I am having the same problem. 
I removed the desklet and installed again, it worked fine for a couple of minutes and then same error...

**Comment by JagArt** [comment]
Такая же проблема

**Comment by JagArt** [comment]
uname -a
Linux aloteq-aloteq001 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Padre2** [comment]
@javahelps.com  Desklet stopped working today - no display, probably after some python package updates.
removed (-) the desklet and added (+) again, showed yellow triangle (!). Unable to configure.
In terminal tried to run `gcalendar`, but would not run.  Reinstalled `gcalendar` from AUR.
Ran `gcalendar` again and ended with notice of missing `aiohttp` package.
Found `python-aiohttpp` package and installed. 
Ran `gcalendar` in terminal and it completed with list of calendar events.
Removed and then re-added the desklet and the events appeared on screen, but not yet in desklet configuration list.
Added calendar events in configuration, but then lost on screen and had error similar to above (see attachment).
Restarting Cinnamon did not fix the problem. Restarted the computer and events displayed.
Rechecked the configuration, which had lost some settings. restarted Cinnamon.
Working normally.  :-)

![calendar_error](https://user-images.githubusercontent.com/38849451/94792903-dc28b380-0403-11eb-8257-f7a502db7f11.png)

**Comment by BrunoGomesCoelho** [comment]
I seem to get this problem about once every few days, I uninstall the desklet, re-start Cinnamon (Alt+F2 then r and enter) and re-install and it goes back to working.

**Comment by siggi747** [comment]
I have the same problem and I found out that it appears every time I have a date for a certain time (hour:minute). As long as the relevant dates are "allday" only everything works fine. Maybe this finding helps to solve the issue

**Comment by LunaManar** [comment]
I have the same experience as @BrunoGomesCoelho. Alt+F2 and r, Enter will successfully refresh my desklet. Seems to be some conflict between the desklet, version of Cinnamon/Mint (Mint 20 users seem less affected from the forum posts I've seen?) and python, but I'm not knowledgeable enough to say exactly where it's breaking other than it seems to happen almost instantly if I try to update any of the visuals--colors, transparency, border margins. If that's when it's breaking for you, try updating the colors/etc to what you would like, then use Alt+F2 and r to restart Cinnamon. This has worked for me thus far. 

You will also have to do this every time you want the calendar to refresh. It will not update on its own and trying to force it in the desklet settings will also cause the error.

**Comment by emmanoe** [comment]
Same problem today with Mint 19

**Comment by NikoKrause** [comment]
ping author @slgobinath

**Comment by slgobinath** [comment]
This problem happens due to the `GLib.spawn_async_with_pipes` call to launch gcalendar. I tried to replace by `GLib.spawn_sync` but I am getting several other issues with synchronized execution. I am working on this issue. I will update here once I find some solution.

@NikoKrause looks like my call to `GLib.spawn_async_with_pipes` does close some resources internally. Can you point me to some sample code that uses `GLib.spawn_async_with_pipes` with proper resource management?

Thanks
