### ISSUE TITLE
[analog-clock@cobinja.de] Python issue in Linux Mint 20  

### ISSUE THREAD

**Issue by milprod** [linuxmint/cinnamon-spices-desklets#574]
```
 * Desklet version/Build date unknown / last update 2019-12-26
 * Cinnamon version (cinnamon --version) 4.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20 Ulyana

 ```

**Notify author of desklet**
analog-clock@cobinja.de

Clock settings seem to need "python", but latest Mint Cinnamon only has python1, python2, python3, etc..
Trying to adjust clock settings gives error "python not found"

**Comment by theesp** [comment]
Same problem here, also on Linux Mint 20.0 'Ulyana'

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/cinnamon-spices-desklets/pull/584/files
