### ISSUE TITLE
soundBox@scollins: PC's CPU RATE AND TEMPERATURE AFFECTED ADVERSLEY BY THIS DESKLET

### ISSUE THREAD

**Issue by Oldbwl** [linuxmint/cinnamon-spices-desklets#580]
```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json") latest
 * Cinnamon version (cinnamon --version) latest
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used Nvidea GTX 1660
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@SCOLLINS

**Issue**
CPU runs at 10% extra and heat at 10deg C more when the Desklet it installed, even if no music player is running.
At Idle, my PC shows 1  - 3% CPU activity and a Temp of 40°C +/- 2 degrees. When the desklet is loaded, the idle rate jumps to a steady 13% and the temp to 50°C

**Steps to reproduce**
Record CPU temp and Average Load.  Load desklet and record new temp and new CPU % load

**Expected behaviour**
A smaller 1 or 2 % increase in either reading is all I would expect

**Other information**
Removing the Desklet and the reading go back to as before

**Comment by NikoKrause** [comment]
ping author @collinss

**Comment by collinss** [comment]
The most likely reason is a bug that was causing it to constantly write to the logs, but I fixed that bug a month or so ago, so I'm going to go ahead and close this. Feel free to reopen this if you still experience the issue after updating to the latest version.
