### ISSUE TITLE
[notes@schorschii] russian translation .mo & .po

### ISSUE THREAD

**Issue by xbow007** [linuxmint/cinnamon-spices-desklets#583]
Hi, i made a translation of this desklet .po into russian. Both ru.po and ru.mo in the attached zip archive.

 * Desklet version: 2.2
[notes@schorschii.zip](https://github.com/linuxmint/cinnamon-spices-desklets/files/5614848/notes%40schorschii.zip)

**Comment by NikoKrause** [comment]
Thanks for the translation, I've uploaded your `ru.po` file.
If you update the desklet, the desklet should be translated now.
