### ISSUE TITLE
diskspace@schorschii: Request for total disk space be displayed above the total used

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-desklets#585]
```
Version 1.12 (2020-10-28 14:40:00)
Cinnamon 4.6.7
Mint 20
Intel i915 
 ```
**Notify author of desklet**
@schorschii 

**Issue**
Suggest that the total disk space be displayed above the total used rather than visa versa.
The center of the circle is larger and it seems more reasonable to put the larger value in the middle between the %used and amount used like:
10%
180.3 G
18.2 G
This might allow for a slightly larger font in the bottom 2 numbers.

**Comment by NikoKrause** [comment]
ping author @schorschii

**Comment by schorschii** [comment]
@ChooChooAl The used space does not always have less characters than the total size and in my point of view it is more convenient to show the total size below the used size. But I added two new options for you so you can choose to display the total size in the middle of the desklet if you want.
