### ISSUE TITLE
system-monitor-graph@rcassani: The latest update does not work with Linux Mint 20.1 Cinnamon

### ISSUE THREAD

**Issue by zappee** [linuxmint/cinnamon-spices-desklets#603]
The latest update does not work with Linux Mint 20.1 Cinnamon. I just updated my Mint Linux, then updated this desklet, and it disappeared. Mint says that "This desklet contains function calls that could potentially cause Cinamon to crash or freeze. If you are expecting crashes or freezing, please try to remove it." 

Could you please fix this? This is my favorite desklet and I would like to use it. Thx.
Version: Version 1.2 (2021-02-06 16:15:34)

**Comment by NikoKrause** [comment]
Hey, there are 45 desklets in this repo.
Which desklet are you talking about?

**Comment by zappee** [comment]
It is called "System monitor graph".

**Comment by NikoKrause** [comment]
ping author @rcassani

**Comment by rcassani** [comment]
@zappee, even with that warning* you should be able to use the Desklet. 
Tested on Linux Mint 20.1 Cinnamon,
Desklet version: 1.2 (2021-02-06 16:15:34)

*The warning has its origin in some readings and subprocesses that are executed synchronously. In the following weeks I'll update the calls to be asynchronous.

**Comment by zappee** [comment]
Thanx. I will try it.
