### ISSUE TITLE
lemondenewspaper@fthuin: Desklet does not work

### ISSUE THREAD

**Issue by icarter09** [linuxmint/cinnamon-spices-desklets#629]
lemondenewspaper@fthuin

 * Most recent build date: 2021-02-06 11:15:34
 * Cinnamon version 4.8.6
 * Mint 20.1 64bit

`(cinnamon:2291): Cjs-CRITICAL **: 23:05:14.131: JS ERROR: TypeError: message.response_body.data is null
_onMessageResponse@/home/turing/.local/share/cinnamon/desklets/lemondenewspaper@fthuin/desklet.js:173:24`

**Notify author of desklet**
@fthuin

**Issue**
Desklet no longer works. 

**Steps to reproduce**
Desklet is unable to load up since the URL to query is no longer working.

**Expected behaviour**
Desklet should work

**Comment by NikoKrause** [comment]
Since there's no response from the author, we probably should remove the desklet.
