### ISSUE TITLE
nepalipatro@deeppradhan: Shows wrong date

### ISSUE THREAD

**Issue by pawanneupane** [linuxmint/cinnamon-spices-desklets#635]
nepalipatro@deeppradhan

```
 * Version 1.0
 * Cinnamon 4.8.6
 * Arch
 
 ```
@kanchudeep

The Nepali Patro desklet shows the previous day's date instead of the current date.

**Comment by shres58tha** [comment]
this will fix it
but not sure why?
https://github.com/linuxmint/cinnamon-spices-desklets/pull/651

**Comment by pawanneupane** [comment]
> this will fix it
> but not sure why?
> #651

Thank you. It's fixed now.
