### ISSUE TITLE
How do you start it?

### ISSUE THREAD

**Issue by SteveM2020** [linuxmint/cinnamon-spices-desklets#650]
```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@

**Issue**
No information on how to start it. How am I supposed to use it?

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by brownsr** [comment]
Sorry, can't do anything with this little information.  Which desklet ?  Or are you asking for help in installing any desklet ? In which case try the forums as issues are to report faults. Closing, so please raise a new issue with at least basic information.

Regards

Simon
