### ISSUE TITLE
bbcwx@oak-wood.co.uk - feature suggestion: adding text shadow

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-desklets#758]
Hi @tipichris, I made a few changes to implement a better contrast in conjunction with 0% background opacity (see screenshots).
I hesitate to make a pull request without asking before, it also has to be reviewd. Are you interested in the code changes?

![Demo without text shadow](https://user-images.githubusercontent.com/9968138/153652964-b723e325-cd51-4050-9290-86c89e84d24b.png)
![Demo with text shadow](https://user-images.githubusercontent.com/9968138/153652960-62fd7511-5311-4d88-b761-07049fda7112.png)

**Comment by gwillgues** [comment]
Go ahead and submit the Pull request, it cant hurt
