### ISSUE TITLE
Yahoo Finance Quotes: Desklet stuck to cursor (transparency error)

### ISSUE THREAD

**Issue by NeuroTypicalCure** [linuxmint/cinnamon-spices-desklets#765]
* Desklet version/Build date (Version 0.8.0 (2022-02-09 20:21:53)
 * Cinnamon version (5.2.7)
 * Distribution - (Linux Mint 20.3)
 * Intel 3rd Gen Core processor Graphics vendor: Lenovo driver: i915
 * ?
 * Snippet or attachment of ~/.xsession-errors (below)

>  Cjs-Message: 06:23:07.981: JS LOG: [LookingGlass/info] Installing settings for yfquotes@thegli
> Cjs-Message: 06:23:07.982: JS LOG: [LookingGlass/info] Settings successfully installed for yfquotes@thegli
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.285: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.286: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.287: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.287: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.288: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.288: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.289: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.289: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.289: Did not find double property 'opacity'
> 
> (cinnamon:2121): St-WARNING **: 06:25:05.290: Did not find double property 'opacity'

**Notify author of desklet**
@thegli 

**Issue**
Sliding transparency setting all the way to the right causes desklet to get stuck to cursor when dragging.

**Steps to reproduce**
1. Change settings>layout>background transparency to 1.00 with slider
2. Drag desklet and try to place it down again

**Expected behaviour**
Not having to remove the desklet

**Other information**
N/A

**Comment by thegli** [comment]
Tried to reproduce the problem but found no problem moving the desklet around with maximum transparency set.
The logged errors suggest that the desklet couldn't find the value for the transparency, but it's unclear to me right now how that can happen.

Can you try to **restore the default settings**?
"Configure.../option menu/Reset to defaults" - you might want to save your original settings first ("Export to a file").
The default transparency is 0.7. Drag the desklet around (this should work), and then change it to maximum 1.0 as you did before, and try again to move it.

**Comment by NeuroTypicalCure** [comment]
Sorry for the late response, I can no longer reproduce the problem either, so I guess this means it solved itself.
