### ISSUE TITLE
Desktop Calculator (calculator@scollins): division not working in RPN mode

### ISSUE THREAD

**Issue by deanajb** [linuxmint/cinnamon-spices-desklets#769]
```
 * Desklet version/Build date: Version 2.0 (2021-09-27 18:21:29)
 * Cinnamon version: 5.2.7
 * Distribution - Linux Mint 20.3
 * Graphics hardware *and* driver:  Intel Core Processor Integrated Graphics Controller, i965 driver
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@collinss 

**Issue**
When in RPN mode, clicking on the division function when two numbers are in the stack does nothing.  Clicking a second time erases the second number.

**Steps to reproduce**
Type  a number, press enter, type a second number, press divide. Nothing happens.

**Expected behaviour**
Result of first number divided by second number.

**Other information**
okay in normal mode.

**Comment by jrversteegh** [comment]
Subtraction also doesn't work

**Comment by schorschii** [comment]
@deanajb Please inform the desklet maintainer next time ([info.json](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/calculator%40scollins/info.json)), this is not necessarily the one in the desklet name.

**Comment by schorschii** [comment]
The README.md of this git repo says: 

> The github username of the author is specified in the spice's info.json file.

But I agree, this info should be added into the issue template and pull request template. What do the repo maintainers think, @rcalixte ?

**Comment by rcalixte** [comment]
> The README.md of this git repo says:
> 
> > The github username of the author is specified in the spice's info.json file.

Per the [Contributing Guidelines](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/.github/CONTRIBUTING.md#reporting-bugs), bugs should be reported per the author's name on the [Cinnamon Spices website](https://cinnamon-spices.linuxmint.com/). The author is correctly identifiable there (e.g. [this desklet](https://cinnamon-spices.linuxmint.com/desklets/view/11))

> But I agree, this info should be added into the issue template and pull request template. What do the repo maintainers think, @rcalixte ?

I'm not aware of any GitHub automation that can process the Author field dynamically from the json files but I'll take a look when I have some time to see what we can improve. There is also a [CODEOWNERS file](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/.github/CODEOWNERS) that is kept reasonably up to date as well. We'll implement the solutions available to us.

**Comment by schorschii** [comment]
> I'm not aware of any GitHub automation that can process the Author field dynamically from the json files

I don't think that an automation is necessary, just a small hint in the [issue template](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/.github/ISSUE_TEMPLATE) that the current desklet maintainer should be taken from the corresponding info.json. The same info could be placed inside a file `.github/PULL_REQUEST_TEMPLATE` for pull requests.

**Comment by rcalixte** [comment]
> > I'm not aware of any GitHub automation that can process the Author field dynamically from the json files
> 
> I don't think that an automation is necessary, just a small hint in the [issue template](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/.github/ISSUE_TEMPLATE) that the current desklet maintainer should be taken from the corresponding info.json. The same info could be placed inside a file `.github/PULL_REQUEST_TEMPLATE` for pull requests.

Right. There are multiple approaches here. Let's choose the more diligent path. I don't believe there is a sense of urgency at the moment.

**Comment by schorschii** [comment]
> Let's choose the more diligent path.

I don't know what you are planning exactly, but implementing an automation for this is over engineered in my opinion.

**Comment by rcalixte** [comment]
> > Let's choose the more diligent path.
> 
> I don't know what you are planning exactly, but implementing an automation for this is over engineered in my opinion.

To a degree, I can see that. But this thread occurred because humans aren't perfect. We can put whatever text in the templates, but that does not ensure the desired output all the time. Automating it once to address the potential issues ideally saves from problems in the future. There's already plenty of automation in place.
