### ISSUE TITLE
[soundBox@scollins] Volume slider has stopped working

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon-spices-desklets#781]
Clicking with mouse on volume slider no longer does anything since cinnamon 5.4.x

Clutter.grab_pointer() not available in cinnamon 5.4.x

@collinss

**Comment by collinss** [comment]
I haven't used this desklet in years. I've been meaning to remove myself as the maintainer of it for a while, but never got around to it. As with the sticky note applet, you're welcome to make whatever changes you'd like to this desklet.
