### ISSUE TITLE
system-monitor-graph@rcassani: new version 1.4 stops working for HDD

### ISSUE THREAD

**Issue by PRSoftware** [linuxmint/cinnamon-spices-desklets#782]
@rcassani

Linux Mint 21 Cinnamon

After upgrading the desklet from version 1.3 to version 1.4, it stops functioning for HDD if the "Filesystem to monitor" is configured as "/" (the root directory of the filesystem).

Error is logged in Looking Glass :

```
error t=2022-08-20T12:32:42Z [Error: Expected type string for argument 'text' but got type number]: Failed to evaluate 'main' function on desklet: system-monitor-graph@rcassani/14
error t=2022-08-20T12:32:43Z 
[system-monitor-graph@rcassani]: Desklet system-monitor-graph@rcassani: Could not create desklet object.
[system-monitor-graph@rcassani]: Error importing desklet.js from system-monitor-graph@rcassani
```
It is ok if this parameter is set to any directory inside the filesystem.

**Comment by rcassani** [comment]
Hey @PRSoftware, it seems is the `Filesystem` label that is returned when doing `$ df /`

Does the problem persist if you put a `Filesystem label` as below?

![image](https://user-images.githubusercontent.com/8238803/185748596-b3726322-e8d8-4932-9c35-d6a7403aebf8.png)

**Comment by PRSoftware** [comment]
Hello Raymundo,

Thanks for your quick answer.

The result of the "df /" command is (my system is configured in French):

```
Sys. de fichiers blocs de 1K    Utilisé Disponible Uti% Monté sur
/dev/sda5         1920696860 1131657744  691399712  63% /
```

I cannot change the "Filesystem label" parameter in the interactive configuration window because the desklet is frozen as soon as I select the root filesystem ("/") in the "Filesystem to monitor" parameter.

To identify and correct the problem, I have manually edited the configuration file (changed the value of the parameter "filesystem" from "/" to "file:///home") and restarted Cinnamon.

**Comment by rcassani** [comment]
@PRSoftware, 
This issue is solved.
Can you close it?
