### ISSUE TITLE
[Wheather Desklet] This desklet not work, please fix it !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-desklets#9]
Hi. I test this desk-let on my laptop. It did not work at all. After I installed it, there appear a red ! inside circle beside desk-let. When I put my mouse over this circle, a message appeared to me said "This extension sand system calls that can lead on certain system to crash DE. If it lead for this please uninstall it"

My system has RAM = 8 GB, & IntelCore i7 5500-U CPU @2.40 x 2 GHz

UUID: bbcwx@oak-wood.co.uk
---------------------------------
It is the same error that was appeared in "Desktop Capture applet" & you kindly fix it.

**Comment by NikoKrause** [comment]
This red ! inside the circle doesn't mean, that this desklet is broken.
It means: "This extension uses system calls that can lead on certain system to crash DE. If it lead for this please uninstall it"

I have the circle as well and the desklet works fine for me on Linux Mint 18.1
Do you have any issues with this desklet except this warning?

If yes, which Linux version do you use?

About the Desktop Capture applet. I don't have a warning for this applet. Which version of the applet are you using? Right click on applet and select "About...". There's an information, which version it is.

**Comment by Nokia808** [comment]
Hi. Sorry for that. 

1) you misunderstood me regarding "Desktop Capture" applet. I did not say it give me warning at this time ! I said it WAS IN THE PAST BEFORE YOU START TO FIX BUGS OF APPLET ! This what I meant. At that time (in past before fix) this applet crash my Cinnamon. For that I post this issue when I saw the warning in Weather Desklet (without test it because already I crashed in PAST by Desktop Capture before you fix it.

2) Regarding "Weather Desklet" I test it & as you said it work without problem. Please delete this post it is false. 

Sorry again.

**Comment by JosephMcc** [comment]
@Nokia808 The warning is just a heads up. If you use the desklet and then start encountering issues like desktop freezing or crashing you should disable the desklet and see if the problems persisit.
