### ISSUE TITLE
Small but noticeable freeze in system-monitor-graph@rcassani

### ISSUE THREAD

**Issue by rcassani** [linuxmint/cinnamon-spices-desklets#913]
* Desklet: ` system-monitor-graph@rcassani`
 * Desklet version: `1.5`
 * Cinnamon version: `5.8.4`
 * Distribution: `Arch`

Last year I (yup, I am the creator of the desklet.) made modifications for in code of the `system-monitor-graph@rcassani`  to remove the synchronous waits (#776). However, it seems there are still calls that cause the desklet to freeze the desktop. This is noticeable when watching a video. 

![image](https://github.com/linuxmint/cinnamon-spices-desklets/assets/8238803/8596a564-02e0-435d-93ac-e91849bbc2ee)

Thus I am opening this issue to ask for support / help to solve (if possible) this behaviour, or to point towards the problem behind it.

Thanks,

**Comment by fredcw** [comment]
I can't test this because I don't have an Nvidia GPU but I don't see anything in your code that would cause a delay. Even if your desklet causes cinnamon to freeze for a short time, this should not cause video to freeze in another app I don't think. I can only guess that the gpu query itself is causing the gpu to freeze.

**Comment by rcalixte** [comment]
I took a look at cleaning up warnings where I could for a few applets/desklets. The challenge here is the [list of unsafe items](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py#L32) that are core for this desklet's functionality, mainly GTop. I haven't found a suitable alternative for libgtop. For all of the other items in the list, there are suitable workarounds.

**Comment by rcassani** [comment]
@fredcw, it seems to be related to the graph drawing. A way to replicated it is to open around 15 graphs (all CPU usage), the short-time freezing is noticeable. Although, it is not realistic to expect that many graphs.

@rcalixte, thanks for tackling the warning. I tested the #914, the behaviour seems to be the same.

Since the freezing is very short when there are few graphs, and the warning is not there anymore. This issue could be closed once the PR is merged.
