### ISSUE TITLE
diskspace@schorshii showing wrong used space and percentage

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-desklets#940]
### Desklet version/Build date

Version 1.14 (2023-10-26 05:57:45)

### Cinnamon version

Cinnamon 5.8.4 

### Distribution

Mint 21.2

### Graphics hardware *and* driver used

Intel graphics

### Desklet name and maintainer

diskspace@schorschii @schorschii

### What happened?

Just recently got updated via mintupdate.
My total used space jumped 4Gs. 

### Other information

I put back the desklet.js and stylesheet.css for Version 1.14 (2023-10-26 05:57:45)
and my disk usage is back to normal.

**Comment by schorschii** [comment]
> My total used space jumped 4Gs

Please give us some more details. Which file system are you monitoring, what is the expected size, what does the desklet shows exactly...

**Comment by ChooChooAl** [comment]
/ filesystem.  
![diskspace okay](https://github.com/linuxmint/cinnamon-spices-desklets/assets/26556059/448fc54f-34b4-4307-a400-ba8ba1c2e94c)
This the old Version 1.14 (2023-10-26 05:57:45)

![diskspace newest](https://github.com/linuxmint/cinnamon-spices-desklets/assets/26556059/c13f3ac0-019a-4913-8e5f-50fdedfa1e82)
Version 1.14 (2023-10-26 05:57:45)

**Comment by schorschii** [comment]
Can you please post the output of `df` and `df -h`? This will tell us the truth.

Due to microstutters on the desktop, the method of how the space is determined was changed recently with v1.14. As side effect, this might cause changed behavior of how reserved blocks are shown. Now, reserved blocks are shown as used space. Before, reserved blocks are not included in used and total space which could be confusing too since the total space shown was not the real total space of the partition. I think it's better to show it as used space, since it is not usable for the normal user.

But there is definitively an issue with the versioning. The version with the old method clearly had v1.13 in its `metadata.json`.

**Comment by ChooChooAl** [comment]
alan: ~ $ df
Filesystem     1K-blocks     Used Available Use% Mounted on
tmpfs            1626676     1820   1624856   1% /run
/dev/nvme0n1p6 104193872 29691260  69163632  31% /
tmpfs            8133376       24   8133352   1% /dev/shm
tmpfs               5120        4      5116   1% /run/lock
/dev/nvme0n1p2     98304    44361     53943  46% /boot/efi
/dev/sdb3      100600660 28976176  66488052  31% /media/alan/Linux
tmpfs            1626672      220   1626452   1% /run/user/1000
 
alan: ~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.6G  1.8M  1.6G   1% /run
/dev/nvme0n1p6  100G   29G   66G  31% /
tmpfs           7.8G   24K  7.8G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/nvme0n1p2   96M   44M   53M  46% /boot/efi
/dev/sdb3        96G   28G   64G  31% /media/alan/Linux
tmpfs           1.6G  220K  1.6G   1% /run/user/1000

The ~30G is the right value  /dev/nvme0n1p6
I've run baobab and system monitor etc and they all report +/- 30 G.  

I keep copies of older versions simply by copying the desklet.js and stylesheet.css.  If you update language info I don't make new copies since those files are not touched.   So I may be injecting a version issue myself.   The bottom line.... and older version gives proper info.
![system monitor](https://github.com/linuxmint/cinnamon-spices-desklets/assets/26556059/53d17e30-caf7-4b32-a9b2-5f90d37febcd)

**Comment by schorschii** [comment]
> The bottom line.... and older version gives proper info

No. It depends on how the application handles reserved blocks. Have a look at the disk in Nemo file manager (right-click -> Properties): it will display the used space exactly as my desklet. It's a matter of opinion which value is more useful for the user.

I think it's more interesting for the end user how many space is effectively available for him - which means to display reserved blocks as used space.

I could agree with adding an option to switch the handling of reserved blocks.

**Comment by ChooChooAl** [comment]
![diskspace from nemo](https://github.com/linuxmint/cinnamon-spices-desklets/assets/26556059/d0eda101-94f7-4be4-b581-49686671cee9)
My Nemo shows 70.8G available, with the old version showing 30.4, add them up it 101.2.  (old diskspace value).
I was going to argue but baobab show 106.7 total on the nvme..p6 so that blows my whole argument since your new version of diskspace also shows 106.7.

So I'll agree the new version is probably the way to go.  It shows more used but with more total. So I still wind up with 70.8G available everywhere.    I really never saw the inconsistencies.  All I saw was the 5G more in diskspace 'used'.  I never looked at the total going up 5G too.
Closed.
