### ISSUE TITLE
[analog-clock@cobinja.de] Feature Request - GPU Temperature

### ISSUE THREAD

**Issue by OphanimLLC** [linuxmint/cinnamon-spices-desklets#951]
### Desklet name and maintainer

analog-clock@cobinja.de @cobinja

### What would you like to see?

GPU Temperature would be amazing!

**Comment by rcalixte** [comment]
@OphanimLLC Have you looked at [Simple System Monitor](https://cinnamon-spices.linuxmint.com/desklets/view/29)? This desklet supports showing the GPU temperature.

**Comment by Cobinja** [comment]
Showing temps is out of the scope of this desklet. Sry.
